export default {
  "Raw-逐字稿-【小Lin求职100问】Data-Analyst和Quant的区别在哪儿Data-A": "Raw_逐字稿_【小Lin求职100问】Data Analyst和Quant的区...",
  "Raw-逐字稿-Why-Wall-Street-is-Ignoring-Big-Techs-Debt": "Raw_逐字稿_Why Wall Street is Ignoring Big ...",
  "Raw-逐字稿-We-Need-To-Talk-About-Leopold": "Raw_逐字稿_We Need To Talk About Leopold",
  "Raw-逐字稿-This-new-startup-can-query-anywhere-youve": "Raw_逐字稿_This new startup can query anywh...",
  "Raw-逐字稿-This-Small-AI-Will-Change-Everything": "Raw_逐字稿_This Small AI Will Change Everyt...",
  "Raw-逐字稿-The-summer-Math-fell-to-the-machines": "Raw_逐字稿_The summer Math fell to the mach...",
  "Raw-逐字稿-The-Insane-US-Japan-Currency-Bailout": "Raw_逐字稿_The Insane US-Japan Currency Bai...",
  "Raw-逐字稿-The-Future-of-AI-in-the-Workplace-Special": "Raw_逐字稿_The Future of AI in the Workplac...",
  "Raw-逐字稿-The-Biggest-Myths-in-Personal-Finance-Rati": "Raw_逐字稿_The Biggest Myths in Personal Fi...",
  "Raw-逐字稿-Stagflation-Explained": "Raw_逐字稿_Stagflation Explained",
  "Raw-逐字稿-Should-you-borrow-to-invest": "Raw_逐字稿_Should you borrow to invest",
  "Raw-逐字稿-Past-the-Point-of-No-Return": "Raw_逐字稿_Past the Point of No Return",
  "Raw-逐字稿-OpenAIs-AI-Agents-Just-Crossed-A-Line": "Raw_逐字稿_OpenAIs AI Agents Just Crossed A...",
  "Raw-逐字稿-How-Much-Would-an-AI-Crash-Destroy": "Raw_逐字稿_How Much Would an AI Crash Destr...",
  "Raw-逐字稿-Here-We-Go-Again": "Raw_逐字稿_Here We Go Again",
  "Raw-逐字稿-Finfluencer-Promotions-Are-Getting-Worse": "Raw_逐字稿_Finfluencer Promotions Are Getti...",
  "Raw-逐字稿-Different-Strengths-Different-Weaknesses": "Raw_逐字稿_Different Strengths  Different W...",
  "Raw-逐字稿-DeepSeeks-AI-Just-Learned-To-Upgrade-Itsel": "Raw_逐字稿_DeepSeeks AI Just Learned To Upg...",
  "Raw-逐字稿-DeepSeek-is-back-and-Silicon-Valley-is-ter": "Raw_逐字稿_DeepSeek is back... and Silicon ...",
  "Raw-逐字稿-DeepSeek-Just-Made-Closed-AI-Look-Ridiculo": "Raw_逐字稿_DeepSeek Just Made Closed AI Loo...",
  "Raw-逐字稿-Claude-AI-Failed-650-Times…Then-Beat-The-H": "Raw_逐字稿_Claude AI Failed 650 Times…Then ...",
  "Raw-逐字稿-Canadas-Condo-Conundrum": "Raw_逐字稿_Canadas Condo Conundrum",
  "Raw-逐字稿-Bill-Bernstein-The-Money-Decisions-That-Ac": "Raw_逐字稿_Bill Bernstein The Money Decisio...",
  "Raw-翻译-🧠-Community-Wisdom-Favorite-Lennys-Product": "🧠 Community Wisdom Favorite Lennys Produ...",
  "Raw-翻译-🎙️-How-I-AI-How-a-solo-founder-used-Codex-a": "🎙️ How I AI How a solo founder used Code...",
  "Raw-翻译-🎙️-How-I-AI-Grok-Bot-Grok-46—whats-great-an": "🎙️ How I AI Grok Bot  Grok 4.6—whats gre...",
  "Raw-翻译-黄金涨破4700美元，但聪明钱在等一次大跌": "黄金涨破4700美元，但聪明钱在等一次大跌",
  "Raw-翻译-马云不再吃瓜": "马云不再吃瓜",
  "Raw-翻译-饮料厂商，谨慎造新": "饮料厂商，谨慎造新",
  "Raw-翻译-飞书连降2级背后，是字节看透了中国ToB的真相": "飞书连降2级背后，是字节看透了中国ToB的真相",
  "Raw-翻译-零食占座争议背后，是国人对火车票的深情与怨念": "零食占座争议背后，是国人对火车票的深情与怨念",
  "Raw-翻译-離婚、智能手機與管控——BBC觀察塔利班如何治理阿富汗": "離婚、智能手機與管控——BBC觀察塔利班如何治理阿富汗",
  "Raw-翻译-造车还在亏损，小鹏就急着讲机器人的故事了": "造车还在亏损，小鹏就急着讲机器人的故事了",
  "Raw-翻译-透视WRC：具身智能本体的权游时刻": "透视WRC：具身智能本体的权游时刻",
  "Raw-翻译-追觅造车一周年：展车地库蒙灰，千人团队剩约百人，烧掉的钱谁来买单": "追觅造车一周年：展车地库蒙灰，千人团队剩约百人，烧掉的钱谁来买单",
  "Raw-翻译-迈威尔Marvell：贴钱结盟谷歌，能撬动博通墙角吗": "迈威尔Marvell：贴钱结盟谷歌，能撬动博通墙角吗",
  "Raw-翻译-越会用-AI-的人，学习能力退化得越快": "越会用 AI 的人，学习能力退化得越快",
  "Raw-翻译-贾樟柯爱上了短剧，文青的天真的塌了": "贾樟柯爱上了短剧，文青的天真的塌了",
  "Raw-翻译-贝森特的真正算盘": "贝森特的真正算盘",
  "Raw-翻译-豆包将推WorkBuddy类产品，飞书十年积累正在组件化": "豆包将推WorkBuddy类产品，飞书十年积累正在组件化",
  "Raw-翻译-调查显示三分之一英文网页有-AI-创作痕迹": "调查显示三分之一英文网页有 AI 创作痕迹",
  "Raw-翻译-访谈过剩的时代，与精力匮乏的争夺": "访谈过剩的时代，与精力匮乏的争夺",
  "Raw-翻译-让-PC-与-HomePod-互联：音频串流工具-WinAirCast": "让 PC 与 HomePod 互联：音频串流工具 WinAirCast",
  "Raw-翻译-西藏—尼泊爾邊境山洪暴發-數百人失蹤": "西藏—尼泊爾邊境山洪暴發 數百人失蹤",
  "Raw-翻译-装了啥特别篇：少数派编辑部最近都-vibe-了啥": "装了啥特别篇：少数派编辑部最近都 vibe 了啥",
  "Raw-翻译-蔡崇信、吴泳铭增持，阿里巴巴美股盘中翻红，800亿港元配售投AI，阿里在下什么棋": "蔡崇信、吴泳铭增持，阿里巴巴美股盘中翻红，800亿港元配售投AI，阿里在下什么棋",
  "Raw-翻译-蓝箭航天会成为中国的SpaceX吗": "蓝箭航天会成为中国的SpaceX吗",
  "Raw-翻译-苹果突袭发布-M6-与-M5-Ultra-芯片与新款-Mac-Mini；字节发布-AI": "苹果突袭发布 M6 与 M5 Ultra 芯片与新款 Mac Mini；字节发布...",
  "Raw-翻译-苹果-Mac-mini-M6-发布：两年涨-2500-块，AI-税反噬「龙虾神机」": "苹果 Mac mini M6 发布：两年涨 2500 块，AI 税反噬「龙虾神机...",
  "Raw-翻译-英伟达押注-Perplexity，但它真的值-300-亿美金吗": "英伟达押注 Perplexity，但它真的值 300 亿美金吗",
  "Raw-翻译-芬兰准备启用全球首座核废料最终处置场": "芬兰准备启用全球首座核废料最终处置场",
  "Raw-翻译-美國制裁伊朗經濟新措施-為何對中國「鬆手」": "美國制裁伊朗經濟新措施 為何對中國「鬆手」",
  "Raw-翻译-美国报告今年的首例麻疹死亡病例": "美国报告今年的首例麻疹死亡病例",
  "Raw-翻译-美国债剧震，终将引发危机": "美国债剧震，终将引发危机",
  "Raw-翻译-美加貿易協議談崩-卡尼面臨關鍵考驗": "美加貿易協議談崩 卡尼面臨關鍵考驗",
  "Raw-翻译-美债利率触发报警，破解困局另有神人": "美债利率触发报警，破解困局另有神人",
  "Raw-翻译-美债利率独创新高：美式化债的序幕": "美债利率独创新高：美式化债的序幕",
  "Raw-翻译-给BBA造车灯的星宇，把应届生逼到向港交所维权": "给BBA造车灯的星宇，把应届生逼到向港交所维权",
  "Raw-翻译-终于要对日本下狠手了": "终于要对日本下狠手了",
  "Raw-翻译-线下活动｜Echoes-Remain：迈克尔杰克逊-68-周年诞辰唱片展": "线下活动｜Echoes Remain：迈克尔杰克逊 68 周年诞辰唱片展",
  "Raw-翻译-科隆游戏展-2026：米哈游出动作游戏，杰洛特又要回来了": "科隆游戏展 2026：米哈游出动作游戏，杰洛特又要回来了",
  "Raw-翻译-离开剪映后创业，她想把一支设计团队装进-AI-工作台": "离开剪映后创业，她想把一支设计团队装进 AI 工作台",
  "Raw-翻译-社媒的设计方式让年轻人难以批判性思考": "社媒的设计方式让年轻人难以批判性思考",
  "Raw-翻译-社区速递-155-适马千元人像神头与七月派友剁手清单": "社区速递 155  适马千元人像神头与七月派友剁手清单",
  "Raw-翻译-硅谷押注的下一个-Harness，是整个桌面操作系统": "硅谷押注的下一个 Harness，是整个桌面操作系统",
  "Raw-翻译-王兴兴错配梁文锋": "王兴兴错配梁文锋",
  "Raw-翻译-特斯拉辟谣数据中心「人去楼空」，但-FSD-仍遥遥无期，特斯拉车主还要等多久": "特斯拉辟谣数据中心「人去楼空」，但 FSD 仍遥遥无期，特斯拉车主还要等多久",
  "Raw-翻译-烏克蘭遭革職防長告訴BBC，該質問澤連斯基對貪腐所知多少": "烏克蘭遭革職防長告訴BBC，該質問澤連斯基對貪腐所知多少",
  "Raw-翻译-灵活就业者社保问题的制度困境和解决出路": "灵活就业者社保问题的制度困境和解决出路",
  "Raw-翻译-灵活就业福利论，遮蔽了什么真问题": "灵活就业福利论，遮蔽了什么真问题",
  "Raw-翻译-澳大利亚是地球最安全的地方": "澳大利亚是地球最安全的地方",
  "Raw-翻译-潮玩文创店，冰火两重天": "潮玩文创店，冰火两重天",
  "Raw-翻译-派评-近期值得关注的-App": "派评  近期值得关注的 App",
  "Raw-翻译-派早报：阿里云视频生成模型-Wan30-上线，小米发布三款玄戒芯片等": "派早报：阿里云视频生成模型 Wan3.0 上线，小米发布三款玄戒芯片等",
  "Raw-翻译-派早报：Apple-发布新款-Mac-mini-和-Mac-Studio-等": "派早报：Apple 发布新款 Mac mini 和 Mac Studio 等",
  "Raw-翻译-泰國南部一夜50多起縱火-軍方稱為有組織搗亂": "泰國南部一夜50多起縱火 軍方稱為有組織搗亂",
  "Raw-翻译-波兰加密货币交易所-CEO-在-2022-年失踪，4-年后他的继任者也失踪了": "波兰加密货币交易所 CEO 在 2022 年失踪，4 年后他的继任者也失踪了",
  "Raw-翻译-欧洲被批量生产的少年杀手们": "欧洲被批量生产的少年杀手们",
  "Raw-翻译-欧洲户外大牌，快被中国企业买光了": "欧洲户外大牌，快被中国企业买光了",
  "Raw-翻译-柳树和杨树释放出的化合物会恶化城市空气质量": "柳树和杨树释放出的化合物会恶化城市空气质量",
  "Raw-翻译-松弛感年轻人：不一定运动，但一定穿运动鞋": "松弛感年轻人：不一定运动，但一定穿运动鞋",
  "Raw-翻译-机器人短跑超越人类，但刹住是问题": "机器人短跑超越人类，但刹住是问题",
  "Raw-翻译-机器人打网球：春晚跳舞真不算啥": "机器人打网球：春晚跳舞真不算啥",
  "Raw-翻译-月入2万以下的家庭，争吵多半和钱有关": "月入2万以下的家庭，争吵多半和钱有关",
  "Raw-翻译-月之暗面与微软、亚马逊和-Google-协商收益分成协议": "月之暗面与微软、亚马逊和 Google 协商收益分成协议",
  "Raw-翻译-普京首登擇捉島：俄羅斯與中國共同牽制日本": "普京首登擇捉島：俄羅斯與中國共同牽制日本",
  "Raw-翻译-早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价158万元LV否认「起诉国家知": "早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价1.58万元LV否认「起...",
  "Raw-翻译-早报｜小米把「OK」藏进玄戒O3雷军不建议拆开看彩蛋vivo官宣X500系列MINI车": "早报｜小米把「OK」藏进玄戒O3,雷军不建议拆开看彩蛋vivo官宣X500系列M...",
  "Raw-翻译-早报｜6999起苹果发布新款Mac-mini追觅官宣收缩探索阶段业务「豆包工作」正式推": "早报｜6999起,苹果发布新款Mac mini追觅官宣收缩探索阶段业务「豆包工作...",
  "Raw-翻译-日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗": "日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗",
  "Raw-翻译-日本经济的大麻烦会变成西方经济的大麻烦": "日本经济的大麻烦会变成西方经济的大麻烦",
  "Raw-翻译-日本出钱，印度高铁为何仍修不动": "日本出钱，印度高铁为何仍修不动",
  "Raw-翻译-新西兰提出法案禁止-16-岁以下儿童使用社媒和-AI-陪伴服务": "新西兰提出法案禁止 16 岁以下儿童使用社媒和 AI 陪伴服务",
  "Raw-翻译-斗胆聊聊阿里老板们的8亿": "斗胆聊聊阿里老板们的8亿",
  "Raw-翻译-教育观察-创新教育的「第三条路」：一场被迫私有化的昂贵自救": "教育观察  创新教育的「第三条路」：一场被迫私有化的昂贵自救",
  "Raw-翻译-摩托罗拉的-GrapheneOS-手机预计比-Pixel-手机更贵": "摩托罗拉的 GrapheneOS 手机预计比 Pixel 手机更贵",
  "Raw-翻译-折叠-iPhone-细节曝光，苹果想折叠的不只是屏幕": "折叠 iPhone 细节曝光，苹果想折叠的不只是屏幕",
  "Raw-翻译-折叠-iPhone-最全爆料汇总：用过的都说好，但有两个大缺点": "折叠 iPhone 最全爆料汇总：用过的都说好，但有两个大缺点",
  "Raw-翻译-手艺还在，手工生产已不再是中心：程序员能力的三次上移": "手艺还在，手工生产已不再是中心：程序员能力的三次上移",
  "Raw-翻译-快時尚品牌Shein赴港上市-估值大減至270億美元": "快時尚品牌Shein赴港上市 估值大減至270億美元",
  "Raw-翻译-快捷指令-让特定-app-小点声：在-iPhone-上实现独立音量控制": "快捷指令  让特定 app 小点声：在 iPhone 上实现独立音量控制",
  "Raw-翻译-德芙文案翻车背后，品牌正在失去对自己的控制": "德芙文案翻车背后，品牌正在失去对自己的控制",
  "Raw-翻译-微软画图和照片应用生成的图像嵌入了看不见的水印": "微软画图和照片应用生成的图像嵌入了看不见的水印",
  "Raw-翻译-微软删除了逾-17-万非营利组织的数据": "微软删除了逾 17 万非营利组织的数据",
  "Raw-翻译-微信灰测「按住转文字」功能被吐槽；DeepSeek-上线多模态功能；应急机械拉手难操作": "微信灰测「按住转文字」功能被吐槽；DeepSeek 上线多模态功能；应急机械拉手...",
  "Raw-翻译-当人形机器人还在学步，四足机器人已经开始领工资了": "当人形机器人还在学步，四足机器人已经开始领工资了",
  "Raw-翻译-当亲手写代码开始被叫作古法编程": "当亲手写代码开始被叫作古法编程",
  "Raw-翻译-当AI开始抽佣：下一代入口的商业模式困局": "当AI开始抽佣：下一代入口的商业模式困局",
  "Raw-翻译-强迫世界选边站队-美国为何要降下AI数字铁幕": "强迫世界选边站队 美国为何要降下AI数字铁幕",
  "Raw-翻译-强如马斯克，也有交白卷的时候": "强如马斯克，也有交白卷的时候",
  "Raw-翻译-张丹丹在学术上是扶不起的，不要再强行挽尊了": "张丹丹在学术上是扶不起的，不要再强行挽尊了",
  "Raw-翻译-弄清中国的消费数据-大视野": "弄清中国的消费数据 大视野",
  "Raw-翻译-开学季-这些软件和服务的教育优惠，能帮你省下不少钱": "开学季  这些软件和服务的教育优惠，能帮你省下不少钱",
  "Raw-翻译-年轻人的网络社交，正在偷偷「鸽化」": "年轻人的网络社交，正在偷偷「鸽化」",
  "Raw-翻译-年轻人的网络社交，正在偷偷鸽化": "年轻人的网络社交，正在偷偷鸽化",
  "Raw-翻译-已知最大星系直径-170-万光年": "已知最大星系直径 170 万光年",
  "Raw-翻译-巨头多日大涨、行业两年没有新玩家，CXO的冰与火之歌": "巨头多日大涨、行业两年没有新玩家，CXO的冰与火之歌",
  "Raw-翻译-小鹏G9L再战高端：这次不缺技术，还缺什么": "小鹏G9L再战高端：这次不缺技术，还缺什么",
  "Raw-翻译-小红书依然是个很容易出利润的平台": "小红书依然是个很容易出利润的平台",
  "Raw-翻译-小米发布玄戒-AI-芯片「全家桶」，还官宣了小米「阔折叠」": "小米发布玄戒 AI 芯片「全家桶」，还官宣了小米「阔折叠」",
  "Raw-翻译-小小的，就很好：年轻人不愿再为过度拥有-买单": "小小的，就很好：年轻人不愿再为过度拥有 买单",
  "Raw-翻译-对话雷鸟创新李宏伟：智能眼镜的终局仍然是「AI-AR」，AI-是我们现在最重要的事丨多": "对话雷鸟创新李宏伟：智能眼镜的终局仍然是「AI  AR」，AI 是我们现在最重要...",
  "Raw-翻译-实测豆包工作：连上飞书后，Agent-终于像个同事了": "实测豆包工作：连上飞书后，Agent 终于像个同事了",
  "Raw-翻译-实测小米-AI-手机：性能超-iPhone，端侧-AI-超级快": "实测小米 AI 手机：性能超 iPhone，端侧 AI 超级快",
  "Raw-翻译-实测开了眼的DeepSeek：认得马斯克，认不出梁文锋": "实测开了眼的DeepSeek：认得马斯克，认不出梁文锋",
  "Raw-翻译-存款搬家暂时降速：2026年1-7月实体部门资金运转观察": "存款搬家暂时降速：2026年1-7月实体部门资金运转观察",
  "Raw-翻译-字节AI-产品向豆包集结，Agent-时代第一场巨头战役打响": "字节AI 产品向豆包集结，Agent 时代第一场巨头战役打响",
  "Raw-翻译-婚姻之外，我们还可以怎样相爱与生活": "婚姻之外，我们还可以怎样相爱与生活",
  "Raw-翻译-大厂AI竞赛，从技术周期走进资本周期": "大厂AI竞赛，从技术周期走进资本周期",
  "Raw-翻译-外卖平台在鼓励吃白食算法失灵下的餐饮低质化": "外卖平台在鼓励吃白食算法失灵下的餐饮低质化",
  "Raw-翻译-在正镶白旗，用五天共同生活理解现代牧场": "在正镶白旗，用五天共同生活理解现代牧场",
  "Raw-翻译-国际计量大会将讨论用闰时取代闰秒": "国际计量大会将讨论用闰时取代闰秒",
  "Raw-翻译-因门把手安全隐患特斯拉在华召回近-300-万辆车": "因门把手安全隐患特斯拉在华召回近 300 万辆车",
  "Raw-翻译-因保安可能罢工-Anthropic-通知员工远程办公": "因保安可能罢工 Anthropic 通知员工远程办公",
  "Raw-翻译-吐槽校区在县城里的大学生，到底想要一所怎样的大学": "吐槽校区在县城里的大学生，到底想要一所怎样的大学",
  "Raw-翻译-台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何": "台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何",
  "Raw-翻译-台湾打工换宿｜用人与人的喜好串起淡水的地图": "台湾打工换宿｜用人与人的喜好串起淡水的地图",
  "Raw-翻译-只为省2000块运费一斤两毛的康保白菜，毁在一桶甲醛上": "只为省2000块运费一斤两毛的康保白菜，毁在一桶甲醛上",
  "Raw-翻译-县城里，靠直播谋生的人": "县城里，靠直播谋生的人",
  "Raw-翻译-厨房纸到底能不能擦吃的": "厨房纸到底能不能擦吃的",
  "Raw-翻译-历史无法预见AI的未来": "历史无法预见AI的未来",
  "Raw-翻译-厄爾尼諾增強：全球海洋溫度創有紀錄以來新高": "厄爾尼諾增強：全球海洋溫度創有紀錄以來新高",
  "Raw-翻译-卡巴斯基发现第一种针对汽车的-Android-恶意程序": "卡巴斯基发现第一种针对汽车的 Android 恶意程序",
  "Raw-翻译-博泰车联网战略转向-进军厨卫数字化": "博泰车联网战略转向 进军厨卫数字化",
  "Raw-翻译-刚刚，新款-Mac-mini-发布价格大涨2500元，苹果第一次为-AI-造电脑": "刚刚，新款 Mac mini 发布价格大涨2500元，苹果第一次为 AI 造电脑",
  "Raw-翻译-分数竞赛：关于Benchmark基准测试的争论和未来": "分数竞赛：关于Benchmark基准测试的争论和未来",
  "Raw-翻译-出海卖爆的风电，现在还是垃圾电吗": "出海卖爆的风电，现在还是垃圾电吗",
  "Raw-翻译-全民播客，一场-精神消费-的虚假繁荣": "全民播客，一场 精神消费 的虚假繁荣",
  "Raw-翻译-债务陷阱加速：美债的深层危机": "债务陷阱加速：美债的深层危机",
  "Raw-翻译-他们追踪2万多中学生发现，AI会让考试成绩大幅下滑": "他们追踪2万多中学生发现，AI会让考试成绩大幅下滑",
  "Raw-翻译-从被找到、被用好到被修好，HarmonyOS-7-给出开发者一套新解法": "从被找到、被用好到被修好，HarmonyOS 7 给出开发者一套新解法",
  "Raw-翻译-从疫苗到航母，最老总统特朗普为什么喜欢老到停产的东西": "从疫苗到航母，最老总统特朗普为什么喜欢老到停产的东西",
  "Raw-翻译-从「告警找人」到「Agent-先接手」，「古茗」如何用-AI-Agent-重构万店运维": "从「告警找人」到「Agent 先接手」，「古茗」如何用 AI Agent 重构万...",
  "Raw-翻译-从WAIC到硅和平，6场国际峰会揭示全球AI治理5大趋势": "从WAIC到硅和平，6场国际峰会揭示全球AI治理5大趋势",
  "Raw-翻译-人形機器人以外，一場中國機器革命正靜悄悄地發生": "人形機器人以外，一場中國機器革命正靜悄悄地發生",
  "Raw-翻译-亚马逊以内存短缺为由大幅上涨自有品硬件产品价格": "亚马逊以内存短缺为由大幅上涨自有品硬件产品价格",
  "Raw-翻译-九成生物医学论文有-AI-辅助写作痕迹": "九成生物医学论文有 AI 辅助写作痕迹",
  "Raw-翻译-中美竞争脱离传统经贸窠臼加速迭代": "中美竞争脱离传统经贸窠臼加速迭代",
  "Raw-翻译-中國青少年濫藥問題：利用處方藥物來「逃避現實」": "中國青少年濫藥問題：利用處方藥物來「逃避現實」",
  "Raw-翻译-中國機器人打破人類百米短跑世界紀錄": "中國機器人打破人類百米短跑世界紀錄",
  "Raw-翻译-中国调整碳强度核算口径，并未弱化其气候承诺": "中国调整碳强度核算口径，并未弱化其气候承诺",
  "Raw-翻译-世界机器人大会观察，银河星脑的愿景：让所有机器人共享「大脑」": "世界机器人大会观察，银河星脑的愿景：让所有机器人共享「大脑」",
  "Raw-翻译-世界上最大的坑": "世界上最大的坑",
  "Raw-翻译-一铲一铲销毁甲醛白菜，康保的菜农：没人来收菜了": "一铲一铲销毁甲醛白菜，康保的菜农：没人来收菜了",
  "Raw-翻译-一边奔向AGI，一边用着敌敌畏消杀：AI能让我们先放心吃口饭吗": "一边奔向AGI，一边用着敌敌畏消杀：AI能让我们先放心吃口饭吗",
  "Raw-翻译-一周世界舆论聚焦：特朗普对朝鲜软硬兼施": "一周世界舆论聚焦：特朗普对朝鲜软硬兼施",
  "Raw-翻译-一台拉高的GT，能让极狐被重新看见吗": "一台拉高的GT，能让极狐被重新看见吗",
  "Raw-翻译-一个比亚迪内部人的独家揭底-中国电车出海的真正隐患": "一个比亚迪内部人的独家揭底 中国电车出海的真正隐患",
  "Raw-翻译-一个小小的追踪器，揭开了AI-公司们隐蔽的角落": "一个小小的追踪器，揭开了AI 公司们隐蔽的角落",
  "Raw-翻译-「米芯」三连发：雷军五年花了-210-亿，归来已「不只手机」": "「米芯」三连发：雷军五年花了 210 亿，归来已「不只手机」",
  "Raw-翻译-「甲醛白菜」再現中國：為何食品安全監管仍有盲區": "「甲醛白菜」再現中國：為何食品安全監管仍有盲區",
  "Raw-翻译-「我感到被騙了」：AI假醫師給台灣老人的震撼教育": "「我感到被騙了」：AI假醫師給台灣老人的震撼教育",
  "Raw-翻译-「AstraTennis」时刻：机器人在全球直播中打了一场真正的网球": "「AstraTennis」时刻：机器人在全球直播中打了一场真正的网球",
  "Raw-翻译-《道路交通安全法》拟大改：「电鸡」限速上调至-20kmh，将严管「暴走团」占道": "《道路交通安全法》拟大改：「电鸡」限速上调至 20kmh，将严管「暴走团」占道",
  "Raw-翻译-《牛来》封神记：烂片名垂影史的三大条件": "《牛来》封神记：烂片名垂影史的三大条件",
  "Raw-翻译-《有头有脸的大模型公司，集体搞起「匿名公测」》": "《有头有脸的大模型公司，集体搞起「匿名公测」》",
  "Raw-翻译-《巫师-3：重制版》正式公开：科隆游戏展-2026-消息汇总": "《巫师 3：重制版》正式公开：科隆游戏展 2026 消息汇总",
  "Raw-翻译-《奥德赛》的焦虑，确实是一种新中产身份证": "《奥德赛》的焦虑，确实是一种新中产身份证",
  "Raw-翻译-又贵又难吃的歹毒漂亮饭，年轻人为什么抢着买单": "又贵又难吃的歹毒漂亮饭，年轻人为什么抢着买单",
  "Raw-翻译-主权AI与词元出海：当中美AI走向全球市场": "主权AI与词元出海：当中美AI走向全球市场",
  "Raw-翻译-The-All-Spark-Cluster-Upgrading-from-16-36": "The All Spark Cluster Upgrading from 16 ...",
  "Raw-翻译-smolmachines-smolvm-as-a-sandbox-for-untrus": "smolmachines  smolvm as a sandbox for un...",
  "Raw-翻译-llm-openrouter-07": "llm-openrouter 0.7",
  "Raw-翻译-llm-anthropic-027": "llm-anthropic 0.27",
  "Raw-翻译-llm-033": "llm 0.33",
  "Raw-翻译-llm-0321": "llm 0.32.1",
  "Raw-翻译-iOS开放生态是中国AI参与国际竞争的基础设施": "iOS开放生态是中国AI参与国际竞争的基础设施",
  "Raw-翻译-iCloud-Hide-My-Email-addresses-will-remain": "iCloud Hide My Email addresses will rema...",
  "Raw-翻译-hdiutil-is-deprecated-in-macOS-27-Golden-Ga": "hdiutil is deprecated in macOS 27 Golden...",
  "Raw-翻译-attune-forms-is-now-on-PyPI-—-and-as-of-thi": "attune-forms is now on PyPI — and as of ...",
  "Raw-翻译-Python-Low-Level-Physical-Media-Storage-Arc": "[Python] Low-Level Physical Media  Stora...",
  "Raw-翻译-AINews-Poolside-gets-12B-reverse-execuhire": "[AINews] Poolside gets $12B reverse-exec...",
  "Raw-翻译-AINews-Memory-prices-up-500-in-12-months": "[AINews] Memory prices up 500 in 12 mont...",
  "Raw-翻译-AINews-Death-of-Params-Zai-CEO-Jie-Tang-on": "[AINews] Death of Params Z.ai CEO Jie Ta...",
  "Raw-翻译-AINews-Andrew-Ng-gets-into-AI-Engineering": "[AINews] Andrew Ng gets into AI Engineer...",
  "Raw-翻译-AINews-10-worse-100x-cheaper-10000x-faster": "[AINews] 10 worse, 100x cheaper, 10000x ...",
  "Raw-翻译-Your-executable-is-a-SQLite-database": "Your executable is a SQLite database",
  "Raw-翻译-Young-Money-Launch-Week-Update": "Young Money Launch Week Update",
  "Raw-翻译-Yesterdays-eclipse-as-seen-from-Spain-simul": "Yesterdays eclipse as seen from Spain, s...",
  "Raw-翻译-Xiaomi-AI-Cube-announced-with-12TBs-memory": "Xiaomi AI Cube announced with 1.2TBs mem...",
  "Raw-翻译-XCancel-also-down-at-least-for-time-being": "XCancel also down, at least for time bei...",
  "Raw-翻译-XCancel-Nitter-收到-X-寄出的终止服务通知": "XCancel Nitter 收到 X 寄出的终止服务通知",
  "Raw-翻译-Windows-是-AI-PC-路上的绊脚石": "Windows 是 AI PC 路上的绊脚石",
  "Raw-翻译-Windows-On-ARM-原生应用少你可以试试这些改造方法": "Windows On ARM 原生应用少你可以试试这些改造方法",
  "Raw-翻译-Wi-Fi-8-专注于提升可靠性": "Wi-Fi 8 专注于提升可靠性",
  "Raw-翻译-Wi-Fi-8-is-the-first-wireless-upgrade-in-ye": "Wi-Fi 8 is the first wireless upgrade in...",
  "Raw-翻译-Why-were-investing-in-Tomo": "Why were investing in Tomo",
  "Raw-翻译-Why-some-US-restaurants-are-banning-tips": "Why some US restaurants are banning tips",
  "Raw-翻译-Why-Chinas-AI-Bubble-Is-Also-Industrial-Pol": "Why Chinas AI Bubble Is Also Industrial ...",
  "Raw-翻译-Where-to-eat-in-San-Francisco": "Where to eat in San Francisco",
  "Raw-翻译-When-strlower-is-a-security-vulnerability-i": "When str.lower is a security vulnerabili...",
  "Raw-翻译-Whats-everyone-working-on-this-week-332026": "Whats everyone working on this week 3320...",
  "Raw-翻译-Whats-Better-Than-Binary-–-Advent-of-Comput": "Whats Better Than Binary – Advent of Com...",
  "Raw-翻译-What-languages-are-agent-skills-written-in": "What languages are agent skills written ...",
  "Raw-翻译-What-it-feels-like-to-work-with-Mythos": "What it feels like to work with Mythos",
  "Raw-翻译-What-is-the-status-of-web-development-in-ru": "What is the status of web development in...",
  "Raw-翻译-What-if-our-biggest-problems-arent-economic": "What if our biggest problems arent econo...",
  "Raw-翻译-What-are-the-best-rules-to-make-cursor-good": "What are the best rules to make cursor g...",
  "Raw-翻译-What-We-Lost-When-Search-Stopped-Making-Us": "What We Lost When Search Stopped Making ...",
  "Raw-翻译-What-Is-a-Harness": "What Is a Harness",
  "Raw-翻译-Weekly-Dose-of-Optimism-207": "Weekly Dose of Optimism 207",
  "Raw-翻译-Weekly-Dose-of-Optimism-206": "Weekly Dose of Optimism 206",
  "Raw-翻译-Weekly-Dose-of-Optimism-205": "Weekly Dose of Optimism 205",
  "Raw-翻译-We-Tracked-a-Shipment-of-Rare-Books-It-Ende": "We Tracked a Shipment of Rare Books. It ...",
  "Raw-翻译-Vintage-Artificial-Intelligence-Before-It-G": "Vintage Artificial Intelligence Before I...",
  "Raw-翻译-Valve-诞生-30-周年": "Valve 诞生 30 周年",
  "Raw-翻译-Using-Local-Coding-Agents": "Using Local Coding Agents",
  "Raw-翻译-Ultra-High-Interactivity-on-NVIDIA-GPUs-Til": "Ultra-High Interactivity on NVIDIA GPUs ...",
  "Raw-翻译-US-data-centers-tripled-annual-water-consum": "US data centers tripled annual water con...",
  "Raw-翻译-US-govt-moves-to-suppress-pushback-on-data": "U.S. govt moves to suppress pushback on ...",
  "Raw-翻译-Trained-a-15B-to-write-shell-commands-so-Id": "Trained a 1.5B to write shell commands s...",
  "Raw-翻译-Tragically-as-many-as-9625-out-of-every-10k": "Tragically, as many as 9625 out of every...",
  "Raw-翻译-Tims中国：成不了星巴克，也学不会瑞幸": "Tims中国：成不了星巴克，也学不会瑞幸",
  "Raw-翻译-TikTok-同意支付-4-亿美元和解美国儿童隐私诉讼": "TikTok 同意支付 4 亿美元和解美国儿童隐私诉讼",
  "Raw-翻译-Thomson-Reuters-Launches-Its-Own-Frontier-M": "Thomson Reuters Launches Its Own Frontie...",
  "Raw-翻译-This-is-a-great-sub-regardless-of-what-comp": "This is a great sub, regardless of what ...",
  "Raw-翻译-The-wayfinder-Skill-Navigating-the-Fog-of-W": "The wayfinder Skill Navigating the Fog o...",
  "Raw-翻译-The-twilight-of-the-chatbots": "The twilight of the chatbots",
  "Raw-翻译-The-end-of-an-era-for-Chinas-economy": "The end of an era for Chinas economy",
  "Raw-翻译-The-death-of-Market-Street": "The death of Market Street",
  "Raw-翻译-The-countdown-to-Qwen38-27B-starts-now": "The countdown to Qwen3.8-27B starts now!",
  "Raw-翻译-The-Supreme-Court-Ruled-Against-Trumps-Tari": "The Supreme Court Ruled Against Trumps T...",
  "Raw-翻译-The-Sloppification-of-Peptides": "The Sloppification of Peptides",
  "Raw-翻译-The-Rise-of-Chinas-Electric-Vehicle-Industr": "The Rise of Chinas Electric Vehicle Indu...",
  "Raw-翻译-The-Religious-Experience-of-Philip-K-Dick-b": "The Religious Experience of Philip K. Di...",
  "Raw-翻译-The-Pulse-Quitting-Spotify-Podcasts-over-re": "The Pulse Quitting Spotify Podcasts over...",
  "Raw-翻译-The-Pulse-Metas-self-inflicted-resignation": "The Pulse Metas self-inflicted resignati...",
  "Raw-翻译-The-Pulse-Groks-CLI-caught-uploading-all-yo": "The Pulse Groks CLI caught uploading all...",
  "Raw-翻译-The-Pulse-Bending-Spoons-Acquisition-Strate": "The Pulse Bending Spoons Acquisition Str...",
  "Raw-翻译-The-Maradona-Theory-of-Interest-Rates": "The Maradona Theory of Interest Rates",
  "Raw-翻译-The-Golden-Rule-for-Becoming-a-Better-Write": "The Golden Rule for Becoming a Better Wr...",
  "Raw-翻译-The-Evolution-of-the-Agent-Harness": "The Evolution of the Agent Harness",
  "Raw-翻译-The-End-of-an-Athlon": "The End of an Athlon",
  "Raw-翻译-The-Best-Charity-of-the-Next-50-Years-Might": "The Best Charity of the Next 50 Years Mi...",
  "Raw-翻译-The-Art-of-Self-Promotion": "The Art of Self-Promotion",
  "Raw-翻译-The-Art-and-Beauty-of-Blade-Runner": "The Art and Beauty of Blade Runner",
  "Raw-翻译-Telegrammar-A-succinct-punny-term-for-conci": "Telegrammar - A succinct, punny term for...",
  "Raw-翻译-Teaching-Everyone-to-Fish-for-Tokens": "Teaching Everyone to Fish for Tokens",
  "Raw-翻译-Taiwans-Modern-Miracle": "Taiwans Modern Miracle",
  "Raw-翻译-TRAE、扣子并入豆包，字节将推「豆包工作」；拓竹回应-2027-年-IPO-传闻：消": "TRAE、扣子并入豆包，字节将推「豆包工作」；拓竹回应 2027 年 IPO 传...",
  "Raw-翻译-TMLR-Relevance-and-Prestige-D": "TMLR Relevance and Prestige [D]",
  "Raw-翻译-Sydney-Marathon-medal-mistakenly-depicts-Mu": "Sydney Marathon medal mistakenly depicts...",
  "Raw-翻译-Students-prefer-Gemini-over-ChatGPT-and-Cla": "Students prefer Gemini over ChatGPT and ...",
  "Raw-翻译-Stop-Just-Stop": "Stop, Just Stop",
  "Raw-翻译-Stop-Making-TUIs": "Stop Making TUIs",
  "Raw-翻译-Software-Engineering-in-the-Agentic-Era": "Software Engineering in the Agentic Era",
  "Raw-翻译-Slovakia-finds-Russian-backdoor-in-traffic": "Slovakia finds Russian backdoor in traff...",
  "Raw-翻译-Slapping-Windows-11-PCs-with-a-Copilot-key": "Slapping Windows 11 PCs with a Copilot k...",
  "Raw-翻译-Simulation-the-new-Scaling-Law-—-Joon-Sung": "Simulation the new Scaling Law — Joon Su...",
  "Raw-翻译-SiFives-First-Server-Platform": "SiFives First Server Platform",
  "Raw-翻译-Show-HN-TexLite-–-A-lightweight-self-hosted": "Show HN TexLite – A lightweight self-hos...",
  "Raw-翻译-Show-HN-TeXbrain-a-LaTeX-editor-that-runs-p": "Show HN TeXbrain, a LaTeX editor that ru...",
  "Raw-翻译-Show-HN-Screen-memory-without-screenshots-j": "Show HN Screen memory without screenshot...",
  "Raw-翻译-Show-HN-Make-your-logo-extra-bright-on-HDR": "Show HN Make your logo extra bright on H...",
  "Raw-翻译-Show-HN-Banking-Access-Index-–-19-US-bankin": "Show HN Banking Access Index – 19 US ban...",
  "Raw-翻译-Show-HN-AgentSight-–-eBPF-observability-for": "Show HN AgentSight – eBPF observability ...",
  "Raw-翻译-Screen-viewing-time-from-age-1-to-8-years-a": "Screen viewing time from age 1 to 8 year...",
  "Raw-翻译-Scientists-release-biggest-2D-map-of-the-un": "Scientists release biggest 2D map of the...",
  "Raw-翻译-Saplings-Unstable-Ground": "Saplings Unstable Ground",
  "Raw-翻译-Samsung-Foundry-updates-process-roadmap-to": "Samsung Foundry updates process roadmap ...",
  "Raw-翻译-SalesPatriot-YC-W25-Is-Hiring-Forward-Deplo": "SalesPatriot YC W25 Is Hiring Forward De...",
  "Raw-翻译-Rust-on-the-JVM-now-passes-99-of-official-u": "Rust on the JVM now passes 99 of officia...",
  "Raw-翻译-Run-It-Hot-Yet-Again": "Run It Hot, Yet Again",
  "Raw-翻译-Rockstar-向微软和-Discord-发去法庭传票以识别-GTA6-泄密者身份": "Rockstar 向微软和 Discord 发去法庭传票以识别 GTA6 泄密者...",
  "Raw-翻译-Roblox-RBLX-Schlep-and-the-Streisand-Effect": "Roblox RBLX Schlep and the Streisand Eff...",
  "Raw-翻译-Rebuilding-our-Electron-meeting-recording-e": "Rebuilding our Electron meeting-recordin...",
  "Raw-翻译-Ranked-The-Worlds-Largest-Gold-Producers-20": "Ranked The Worlds Largest Gold Producers...",
  "Raw-翻译-Ranked-The-Worlds-Largest-Cities-1950-2100": "Ranked The Worlds Largest Cities 1950-21...",
  "Raw-翻译-Ranked-The-Worlds-Busiest-Airlines-by-Fligh": "Ranked The Worlds Busiest Airlines by Fl...",
  "Raw-翻译-Ranked-The-Most-Popular-AI-Tools-in-2026": "Ranked The Most Popular AI Tools in 2026",
  "Raw-翻译-Ranked-The-Highest-Mountain-on-Every-Contin": "Ranked The Highest Mountain on Every Con...",
  "Raw-翻译-Ranked-The-Biggest-Risks-to-the-US-Economy": "Ranked The Biggest Risks to the U.S. Eco...",
  "Raw-翻译-Ranked-The-20-Highest-Grossing-Concert-Tour": "Ranked The 20 Highest-Grossing Concert T...",
  "Raw-翻译-Ranked-Military-Spending-in-OECD-Countries": "Ranked Military Spending in OECD Countri...",
  "Raw-翻译-Ranked-Countries-With-the-Highest-Senior-Po": "Ranked Countries With the Highest Senior...",
  "Raw-翻译-Ranked-Car-Brands-With-the-Most-Loyal-Custo": "Ranked Car Brands With the Most Loyal Cu...",
  "Raw-翻译-QwenQwen38-27B-·-released": "QwenQwen3.8-27B · released",
  "Raw-翻译-Qwen38-Flash-Next-This-architecture-could-b": "Qwen3.8-Flash-Next. This architecture co...",
  "Raw-翻译-Qwen38-27B-is-identical-to-Qwen36-27B": "Qwen3.8-27B is identical to Qwen3.6-27B",
  "Raw-翻译-Qwen38-27B-Q6-is-a-beast-at-agentic-coding": "Qwen3.8-27B Q6 is a beast at agentic cod...",
  "Raw-翻译-Qwen-38-27B-scores-52-on-the-Artificial-Ana": "Qwen 3.8 27B scores 52 on the Artificial...",
  "Raw-翻译-Qwen-38-27B-is-a-game-changer": "Qwen 3.8 27B is a game changer",
  "Raw-翻译-Qwen-38-27B-Released-Please-Share-Your-Expe": "Qwen 3.8 27B Released Please Share Your ...",
  "Raw-翻译-Quoting-Paul-Dix": "Quoting Paul Dix",
  "Raw-翻译-Quoting-Matt-Webb": "Quoting Matt Webb",
  "Raw-翻译-Quoting-Linus-Torvalds": "Quoting Linus Torvalds",
  "Raw-翻译-Quoting-Drew-Breunig": "Quoting Drew Breunig",
  "Raw-翻译-Queryable-Executables": "Queryable Executables",
  "Raw-翻译-Quantum-battery-upends-the-rules-of-chargin": "Quantum battery upends the rules of char...",
  "Raw-翻译-Pythons-pre-declared-constants-are-kinda-we": "Pythons pre-declared constants are kinda...",
  "Raw-翻译-Post-Dilution-Performance": "Post-Dilution Performance",
  "Raw-翻译-Pitchfork0分警告：音乐作者性正在被AI淹没": "Pitchfork0分警告：音乐作者性正在被AI淹没",
  "Raw-翻译-Pgbot-A-59-MB-read-only-Postgres-tool-for-h": "Pgbot A 5.9 MB read-only Postgres tool f...",
  "Raw-翻译-PayPal-Declined": "PayPal, Declined",
  "Raw-翻译-Overcaffeinated-in-Indonesia": "Overcaffeinated in Indonesia",
  "Raw-翻译-Over-Target": "Over Target",
  "Raw-翻译-Other-Python-forums-Stack-Overflow": "Other Python forums - Stack Overflow",
  "Raw-翻译-OpenAI「亲儿子」反水，认中国模型做「赛博义父」": "OpenAI「亲儿子」反水，认中国模型做「赛博义父」",
  "Raw-翻译-OpenAI-首款自研推理芯片-Jalapeño-强于英伟达-Blackwell": "OpenAI 首款自研推理芯片 Jalapeño 强于英伟达 Blackwell",
  "Raw-翻译-OpenAI-自研「辣椒芯片」首测超英伟达，会让-ChatGPT-更便宜吗": "OpenAI 自研「辣椒芯片」首测超英伟达，会让 ChatGPT 更便宜吗",
  "Raw-翻译-OpenAI-Jalapeño-Better-Than-Nvidia-Blackwel": "OpenAI Jalapeño Better Than Nvidia Black...",
  "Raw-翻译-One-corner-of-Chinas-internet-is-insisting": "One corner of Chinas internet is insisti...",
  "Raw-翻译-One-Go-binary-one-YAML-file-one-SQLite-data": "One Go binary, one YAML file, one SQLite...",
  "Raw-翻译-Oldinsurancemapsnet-is-now-a-Charter-Projec": "Oldinsurancemaps.net is now a Charter Pr...",
  "Raw-翻译-North-Korean-Messiah": "North Korean Messiah",
  "Raw-翻译-Netflix-to-Sell-Streaming-Services-Streamer": "Netflix to Sell Streaming Services, Stre...",
  "Raw-翻译-NetBSD-and-My-Life-2005": "NetBSD and My Life 2005",
  "Raw-翻译-Nebula-Sans": "Nebula Sans",
  "Raw-翻译-NanoGPT-Speedrun-Frontier": "NanoGPT Speedrun Frontier",
  "Raw-翻译-More-than-just-code-review": "More than just code review",
  "Raw-翻译-More-than-half-of-adults-in-US-say-they-lac": "More than half of adults in U.S. say the...",
  "Raw-翻译-Moon-2024": "Moon 2024",
  "Raw-翻译-MiniMax-Music3-released": "MiniMax-Music3 released!",
  "Raw-翻译-Markdown-SVG-upgrades": "Markdown SVG upgrades",
  "Raw-翻译-Marginal-Rations": "Marginal Rations",
  "Raw-翻译-Mapped-Where-Young-Americans-Are-Buying-Hom": "Mapped Where Young Americans Are Buying ...",
  "Raw-翻译-Mapped-Where-Homelessness-Rates-Are-Highest": "Mapped Where Homelessness Rates Are High...",
  "Raw-翻译-Malware-infects-Android-based-automotive-he": "Malware infects Android-based automotive...",
  "Raw-翻译-Maiao-Gerrit-style-code-review-workflow-for": "Maiao Gerrit-style code review workflow ...",
  "Raw-翻译-Made-a-cake-for-my-boyfriends-birthday": "Made a cake for my boyfriends birthday",
  "Raw-翻译-LiteLLM-YC-W23-Is-Hiring-–-Rust-Performance": "LiteLLM YC W23 Is Hiring – Rust  Perform...",
  "Raw-翻译-Linux-诞生-35-周年": "Linux 诞生 35 周年",
  "Raw-翻译-Letter-from-Dolly-Parton-to-Eminem": "Letter from Dolly Parton to Eminem",
  "Raw-翻译-Leopolds-Fall": "Leopolds Fall",
  "Raw-翻译-Learning-about-The-Unix-Time-Sharing-System": "Learning about The Unix Time-Sharing Sys...",
  "Raw-翻译-LLMs-could-control-their-host-machines-by-e": "LLMs could control their host machines b...",
  "Raw-翻译-Knowing-When-to-Stop-The-Art-of-Making-a-Lo": "Knowing When to Stop The Art of Making a...",
  "Raw-翻译-Kimi涨价、OpenAI降价：中国土AI冲击美国山大王": "Kimi涨价、OpenAI降价：中国土AI冲击美国山大王",
  "Raw-翻译-Japan-tried-to-build-an-operating-system-fo": "Japan tried to build an operating system...",
  "Raw-翻译-JIT-Compiling-Code-in-5μs": "JIT Compiling Code in 5μs",
  "Raw-翻译-Initial-focus-for-our-partnership-with-Moto": "Initial focus for our partnership with M...",
  "Raw-翻译-Increased-included-usage-and-update-to-Auto": "Increased included usage and update to A...",
  "Raw-翻译-Import-AI-470-No-rights-for-machines;-autom": "Import AI 470 No rights for machines; au...",
  "Raw-翻译-Import-AI-469-Science-AI;-RSI-simulator;-an": "Import AI 469 Science AI; RSI simulator;...",
  "Raw-翻译-Import-AI-468-23-RSI-ideas;-PostTrainBench;": "Import AI 468 23 RSI ideas; PostTrainBen...",
  "Raw-翻译-Import-AI-467-Self-sustaining-AI-viruses;-p": "Import AI 467 Self-sustaining AI viruses...",
  "Raw-翻译-ITS-OUT": "ITS OUT",
  "Raw-翻译-I-wrote-an-AI-textbook-—-how-long-until-AI": "I wrote an AI textbook — how long until ...",
  "Raw-翻译-I-tested-Grok-Bot-Grok-46-and-Cursor-Origin": "I tested Grok Bot, Grok 4.6, and Cursor ...",
  "Raw-翻译-I-spent-20000-on-Devin-in-a-month-Heres-wha": "I spent $20,000 on Devin in a month. Her...",
  "Raw-翻译-I-gave-Qwen-38-27B-a-reverse-engineering-jo": "I gave Qwen 3.8 27B a reverse-engineerin...",
  "Raw-翻译-I-compiled-Dooms-renderer-into-a-21B-parame": "I compiled Dooms renderer into a 21B-par...",
  "Raw-翻译-How-to-figure-out-your-next-career-move": "How to figure out your next career move",
  "Raw-翻译-How-to-close-100K-enterprise-deals-step-by": "How to close $100K enterprise deals, ste...",
  "Raw-翻译-How-much-of-HN-is-AI": "How much of HN is AI",
  "Raw-翻译-How-is-the-qmusage-quota-for-Grok-46-in-cur": "How is the qmusage quota for Grok 4.6 in...",
  "Raw-翻译-How-Universities-Should-Prepare-Founders": "How Universities Should Prepare Founders",
  "Raw-翻译-How-Claude-Watermarks-AI-Generated-Text": "How Claude Watermarks AI-Generated Text",
  "Raw-翻译-How-AI-Becomes-a-Political-Crisis": "How AI Becomes a Political Crisis",
  "Raw-翻译-Hook-hold-harvest-and-hide-Metas-alleged-st": "Hook, hold, harvest and hide Metas alleg...",
  "Raw-翻译-Hey-Rustaceans-Got-a-question-Ask-here-3320": "Hey Rustaceans Got a question Ask here 3...",
  "Raw-翻译-Here-Comes-the-Repo-Man": "Here Comes the Repo Man",
  "Raw-翻译-Headlong-A-Microharness-for-Persistent-Agen": "Headlong A Microharness for Persistent A...",
  "Raw-翻译-Harvest-IBM-7950-Supercomputer-for-cryptana": "Harvest IBM 7950 Supercomputer for crypt...",
  "Raw-翻译-Great-Scott": "Great Scott",
  "Raw-翻译-GraphWorkflow-提速625-后，Agent-蜂群真正要解决什么": "GraphWorkflow 提速62.5 后，Agent 蜂群真正要解决什么",
  "Raw-翻译-Github-unslothai-unsloth": "Github__unslothai_unsloth",
  "Raw-翻译-Github-tt-a1i-archify": "Github__tt-a1i_archify",
  "Raw-翻译-Github-smicallef-spiderfoot": "Github__smicallef_spiderfoot",
  "Raw-翻译-Github-openai-codex": "Github__openai_codex",
  "Raw-翻译-Github-obra-superpowers": "Github__obra_superpowers",
  "Raw-翻译-Github-modular-modular": "Github__modular_modular",
  "Raw-翻译-Github-megadose-holehe": "Github__megadose_holehe",
  "Raw-翻译-Github-mattpocock-skills": "Github__mattpocock_skills",
  "Raw-翻译-Github-freestylefly-awesome-gpt-image-2": "Github__freestylefly_awesome-gpt-image-2",
  "Raw-翻译-Github-cursor-plugins": "Github__cursor_plugins",
  "Raw-翻译-Github-cordiverse-cordis": "Github__cordiverse_cordis",
  "Raw-翻译-Github-basecamp-omarchy": "Github__basecamp_omarchy",
  "Raw-翻译-Github-apache-maka": "Github__apache_maka",
  "Raw-翻译-Github-anthropics-claude-plugins-community": "Github__anthropics_claude-plugins-commun...",
  "Raw-翻译-Github-affaan-m-ECC": "Github__affaan-m_ECC",
  "Raw-翻译-Github-Wei-Shaw-sub2api": "Github__Wei-Shaw_sub2api",
  "Raw-翻译-Github-TauricResearch-TradingAgents": "Github__TauricResearch_TradingAgents",
  "Raw-翻译-Github-AprilNEA-OpenLogi": "Github__AprilNEA_OpenLogi",
  "Raw-翻译-Gen15-模型带来重要进展：物理-AI-正在接近-GPT3-时刻": "Gen1.5 模型带来重要进展：物理 AI 正在接近 GPT3 时刻",
  "Raw-翻译-GLM-53-How-Chinese-labs-keep-stride-with-th": "GLM-5.3 How Chinese labs keep stride wit...",
  "Raw-翻译-GLM-53-Released": "GLM 5.3 Released",
  "Raw-翻译-Friday-Daily-Thread-rPython-Meta-and-Free-T": "Friday Daily Thread rPython Meta and Fre...",
  "Raw-翻译-For-the-people-who-got-reviews-back-from-ne": "For the people who got reviews back from...",
  "Raw-翻译-Fixed-Jinja-chat-template-for-Qwen-35-36-an": "Fixed Jinja chat template for Qwen 3.5, ...",
  "Raw-翻译-Financing-the-AI-Boom-3": "Financing the AI Boom 3",
  "Raw-翻译-Fast-and-Hard-Code": "Fast and Hard Code",
  "Raw-翻译-Endangered-Specious": "Endangered Specious",
  "Raw-翻译-Economists-should-be-worried-about-birth-ra": "Economists should be worried about birth...",
  "Raw-翻译-Early-Humans-Likely-Ate-Carbs-and-Sugary-Fo": "Early Humans Likely Ate Carbs and Sugary...",
  "Raw-翻译-EVE-Online-The-Move-to-Python-3-Begins": "EVE Online The Move to Python 3 Begins",
  "Raw-翻译-EU-GPU-prices-are-up-19-in-one-month-tracke": "EU GPU prices are up ~19 in one month, t...",
  "Raw-翻译-Dolly-Parton-Has-Died": "Dolly Parton Has Died",
  "Raw-翻译-Disruption-with-Some-GitHub-Services": "Disruption with Some GitHub Services",
  "Raw-翻译-Dirty-Secrets-Eight-SMIDs": "Dirty Secrets Eight SMIDs",
  "Raw-翻译-Digging-the-grave-of-my-skills-Hollywood-cr": "Digging the grave of my skills Hollywood...",
  "Raw-翻译-DeepSeek-周末用量统一低价收费；特斯拉-9-月-3-日首秀-Cybercab；": "DeepSeek 周末用量统一低价收费；特斯拉 9 月 3 日首秀 Cyberc...",
  "Raw-翻译-Debian-polls-its-developers-on-AI-permit-or": "Debian polls its developers on AI permit...",
  "Raw-翻译-Controlling-Reasoning-Effort-in-LLMs": "Controlling Reasoning Effort in LLMs",
  "Raw-翻译-Collaborative-Fund-Conversations-Jacob-Hode": "Collaborative Fund Conversations Jacob H...",
  "Raw-翻译-Claudette-Make-Claude-Stop-Talking-Like-a-B": "Claudette Make Claude Stop Talking Like ...",
  "Raw-翻译-Clara-YC-P26-Is-Hiring-a-Growth-Engineer-to": "Clara YC P26 Is Hiring a Growth Engineer...",
  "Raw-翻译-City2Graph-A-Python-library-for-Heterogeneo": "City2Graph A Python library for Heteroge...",
  "Raw-翻译-ChatGPT-search-now-uses-the-siteoperator-at": "ChatGPT search now uses the siteoperator...",
  "Raw-翻译-Cerebrass-Next-Generation-CS-4-Fast-Just-Go": "Cerebrass Next Generation CS-4 Fast Just...",
  "Raw-翻译-Cancer-Related-Mortality-Among-US-Pilots-an": "Cancer-Related Mortality Among US Pilots...",
  "Raw-翻译-Canada-suspends-trade-negotiations-with-USA": "Canada suspends trade negotiations with ...",
  "Raw-翻译-C2PA-Cameras-Do-Not-Survive-Contact-with-Re": "C2PA Cameras Do Not Survive Contact with...",
  "Raw-翻译-Building-an-AI-Text-Detector-From-Scratch": "Building an AI Text Detector From Scratc...",
  "Raw-翻译-Bringing-the-cybersecurity-capabilities-of": "Bringing the cybersecurity capabilities ...",
  "Raw-翻译-Belgian-car-salesman-becomes-prince-after-D": "Belgian car salesman becomes prince afte...",
  "Raw-翻译-Base-Power-Company-Chapter-3": "Base Power Company Chapter 3",
  "Raw-翻译-Autonomy-and-Innovation": "Autonomy and Innovation",
  "Raw-翻译-Authoritarianism-of-Code": "Authoritarianism of Code",
  "Raw-翻译-Ask-HN-What-is-one-simple-thing-LLMs-are-in": "Ask HN What is one simple thing LLMs are...",
  "Raw-翻译-Ask-HN-Good-large-format-20-inches-touchscr": "Ask HN Good large format 20 inches touch...",
  "Raw-翻译-Are-we-watching-the-US-go-bankrupt": "Are we watching the U.S. go bankrupt",
  "Raw-翻译-Are-Open-Models-Catching-Up": "Are Open Models Catching Up",
  "Raw-翻译-Apple-Updates-Mini-and-Studio-AI-Computers": "Apple Updates Mini and Studio, AI Comput...",
  "Raw-翻译-Apple-Mac-Studio-M5-Ultra-with-12TBS-Memory": "Apple Mac Studio M5 Ultra with 1.2TBS Me...",
  "Raw-翻译-Apple-Introduces-New-Mac-Studio-with-M5-Max": "Apple Introduces New Mac Studio with M5 ...",
  "Raw-翻译-App1｜ArkFlow：满足你的卡面收集癖，给信用卡做个卡面墙": "App1｜ArkFlow：满足你的卡面收集癖，给信用卡做个卡面墙",
  "Raw-翻译-Anthropics-best-AI-model-struggles-to-attra": "Anthropics best AI model struggles to at...",
  "Raw-翻译-Anthropic-最强模型难以吸引用户": "Anthropic 最强模型难以吸引用户",
  "Raw-翻译-Anthropic-appears-to-be-AB-testing-reduced": "Anthropic appears to be AB testing reduc...",
  "Raw-翻译-Another-Better-Lower-Bound-for-N17-Square-P": "Another Better Lower Bound for N17 Squar...",
  "Raw-翻译-Announcing-Lennys-Jobs-The-best-place-in-th": "Announcing Lennys Jobs The best place in...",
  "Raw-翻译-An-opinionated-guide-to-which-AI-to-use-to": "An opinionated guide to which AI to use ...",
  "Raw-翻译-An-American-Engineer-in-China": "An American Engineer in China",
  "Raw-翻译-Americas-Electricity-Gap": "Americas Electricity Gap",
  "Raw-翻译-All-You-Need-To-Know-About-Warsh": "All You Need To Know About Warsh",
  "Raw-翻译-Agentic-Context-Management-Memory-and-Cost": "Agentic Context Management Memory and Co...",
  "Raw-翻译-AgentX-InferenceXv3-Does-CUDA-Moat-Hold-up": "AgentX - InferenceXv3 Does CUDA Moat Hol...",
  "Raw-翻译-AWS-Acquires-DuckDB": "AWS Acquires DuckDB",
  "Raw-翻译-AMDs-FP64-Boost-with-MI430X-Is-Even-Bigger": "AMDs FP64 Boost with MI430X Is Even Bigg...",
  "Raw-翻译-AI的账单，不只由科技公司买单": "AI的账单，不只由科技公司买单",
  "Raw-翻译-AI时代，我们可能都要走向灵活就业": "AI时代，我们可能都要走向灵活就业",
  "Raw-翻译-AI代笔风潮之下的讨论和思考（上）": "AI代笔风潮之下的讨论和思考（上）",
  "Raw-翻译-AI-时代的-Surface-Pro-7-改造指南：看板、轻量工作站与-Linux-笔": "AI 时代的 Surface Pro 7 改造指南：看板、轻量工作站与 Linu...",
  "Raw-翻译-AI-开始给自己造芯了，OpenAI-只用了九个月": "AI 开始给自己造芯了，OpenAI 只用了九个月",
  "Raw-翻译-AI-原生企业：不是企业-AI": "AI 原生企业：不是企业  AI",
  "Raw-翻译-AI-即将接管流量，而广告正在疯狂「末日反扑」": "AI 即将接管流量，而广告正在疯狂「末日反扑」",
  "Raw-翻译-AI-助力改造非智能升降桌：智能升降、语音控制、多端联动……": "AI 助力改造非智能升降桌：智能升降、语音控制、多端联动……",
  "Raw-翻译-AI-for-Science最难学会的，是换一个问题": "AI for Science最难学会的，是换一个问题",
  "Raw-翻译-AI-Got-Good-at-Language-Now-Its-Learning-th": "AI Got Good at Language. Now Its Learnin...",
  "Raw-翻译-A-shot-scraper-style-JSON-API-on-Bun-14s-ne": "A shot-scraper-style JSON API on Bun 1.4...",
  "Raw-翻译-A-preliminary-Qwen38-27B-model-card-is-live": "A preliminary Qwen3.8-27B model card is ...",
  "Raw-翻译-A-formal-degree-and-algorithmic-problem-sol": "A formal degree and algorithmic problem-...",
  "Raw-翻译-A-Minor-Detail": "A Minor Detail",
  "Raw-翻译-A-Kantian-Critique-of-Sorry-by-Justin-Biebe": "A Kantian Critique of Sorry by Justin Bi...",
  "Raw-翻译-A-Friendly-Introduction-to-Racket": "A Friendly Introduction to Racket",
  "Raw-翻译-99元AI洗头、499元AI按摩…体验完深圳5款AI大保健，我碎了": "9.9元AI洗头、49.9元AI按摩…体验完深圳5款AI大保健，我碎了",
  "Raw-翻译-7月宏观数据给了什么样的信号": "7月宏观数据给了什么样的信号",
  "Raw-翻译-535B大模型直播训练三个月：代码、数据、Loss全公开，吴恩达公开力挺": "535B大模型直播训练三个月：代码、数据、Loss全公开，吴恩达公开力挺",
  "Raw-翻译-4天消失2000亿，宇树为何遭遇抛售": "4天消失2000亿，宇树为何遭遇抛售",
  "Raw-翻译-3万店之后，鸣鸣很忙还有什么弹药": "3万店之后，鸣鸣很忙还有什么弹药",
  "Raw-翻译-38x-in-Ten-Months-Inside-One-of-Fintechs-Fa": "38x in Ten Months Inside One of Fintechs...",
  "Raw-翻译-32-亿人口、9-万亿元市场，做餐饮也要开始抢老人了": "3.2 亿人口、9 万亿元市场，做餐饮也要开始抢老人了",
  "Raw-翻译-3-分钟冲刺跑产生的分子反应与-90-分钟中等强度运动截然不同": "3 分钟冲刺跑产生的分子反应与 90 分钟中等强度运动截然不同",
  "Raw-翻译-29-Year-Olds-Can-Write-Memoirs-Too": "29-Year-Olds Can Write Memoirs Too",
  "Raw-翻译-2798-万元起，泰钽-700-正式上市，越野-NOA-开上挂壁公路": "27.98 万元起，泰钽 700 正式上市，越野 NOA 开上挂壁公路",
  "Raw-翻译-23-low-regret-recommendations-for-AI-policy": "23 low-regret recommendations for AI pol...",
  "Raw-翻译-202634-App-Snore": "2026.34 App Snore",
  "Raw-翻译-202633-The-CapEx-Train-Keeps-Rolling": "2026.33 The CapEx Train Keeps Rolling",
  "Raw-翻译-130-亿美元，Hugging-Face-要卖了": "130 亿美元，Hugging Face 要卖了",
  "Raw-翻译-12B-of-US-ratepayers-money-wasted-on-a-mode": "$12B of US ratepayers money wasted on a ...",
  "Raw-微信-猫笔刀-算一笔烂账": "Raw_微信_猫笔刀_算一笔烂账",
  "Auto-简报-🧠-Community-Wisdom-Favorite-Lennys-Product": "🧠 Community Wisdom Favorite Lennys Produ...",
  "Auto-简报-🎙️-How-I-AI-How-a-solo-founder-used-Codex": "🎙️ How I AI How a solo founder used Code...",
  "Auto-简报-🎙️-How-I-AI-Grok-Bot-Grok-46—whats-great-a": "🎙️ How I AI Grok Bot  Grok 4.6—whats gre...",
  "Auto-简报-黄金涨破4700美元，但聪明钱在等一次大跌": "黄金涨破4700美元，但聪明钱在等一次大跌",
  "Auto-简报-马云不再吃瓜": "马云不再吃瓜",
  "Auto-简报-饮料厂商，谨慎造新": "饮料厂商，谨慎造新",
  "Auto-简报-飞书连降2级背后，是字节看透了中国ToB的真相": "飞书连降2级背后，是字节看透了中国ToB的真相",
  "Auto-简报-零食占座争议背后，是国人对火车票的深情与怨念": "零食占座争议背后，是国人对火车票的深情与怨念",
  "Auto-简报-離婚、智能手機與管控——BBC觀察塔利班如何治理阿富汗": "離婚、智能手機與管控——BBC觀察塔利班如何治理阿富汗",
  "Auto-简报-造车还在亏损，小鹏就急着讲机器人的故事了": "造车还在亏损，小鹏就急着讲机器人的故事了",
  "Auto-简报-透视WRC：具身智能本体的权游时刻": "透视WRC：具身智能本体的权游时刻",
  "Auto-简报-追觅造车一周年：展车地库蒙灰，千人团队剩约百人，烧掉的钱谁来买单": "追觅造车一周年：展车地库蒙灰，千人团队剩约百人，烧掉的钱谁来买单",
  "Auto-简报-越会用-AI-的人，学习能力退化得越快": "越会用 AI 的人，学习能力退化得越快",
  "Auto-简报-贾樟柯爱上了短剧，文青的天真的塌了": "贾樟柯爱上了短剧，文青的天真的塌了",
  "Auto-简报-贝森特的真正算盘": "贝森特的真正算盘",
  "Auto-简报-豆包将推WorkBuddy类产品，飞书十年积累正在组件化": "豆包将推WorkBuddy类产品，飞书十年积累正在组件化",
  "Auto-简报-调查显示三分之一英文网页有-AI-创作痕迹": "调查显示三分之一英文网页有 AI 创作痕迹",
  "Auto-简报-访谈过剩的时代，与精力匮乏的争夺": "访谈过剩的时代，与精力匮乏的争夺",
  "Auto-简报-西藏—尼泊爾邊境山洪暴發-數百人失蹤": "西藏—尼泊爾邊境山洪暴發 數百人失蹤",
  "Auto-简报-装了啥特别篇：少数派编辑部最近都-vibe-了啥": "装了啥特别篇：少数派编辑部最近都 vibe 了啥",
  "Auto-简报-蔡崇信、吴泳铭增持，阿里巴巴美股盘中翻红，800亿港元配售投AI，阿里在下什么棋": "蔡崇信、吴泳铭增持，阿里巴巴美股盘中翻红，800亿港元配售投AI，阿里在下什么棋",
  "Auto-简报-蓝箭航天会成为中国的SpaceX吗": "蓝箭航天会成为中国的SpaceX吗",
  "Auto-简报-苹果突袭发布-M6-与-M5-Ultra-芯片与新款-Mac-Mini；字节发布-A": "苹果突袭发布 M6 与 M5 Ultra 芯片与新款 Mac Mini；字节发布...",
  "Auto-简报-苹果-Mac-mini-M6-发布：两年涨-2500-块，AI-税反噬「龙虾神机」": "苹果 Mac mini M6 发布：两年涨 2500 块，AI 税反噬「龙虾神机...",
  "Auto-简报-英伟达押注-Perplexity，但它真的值-300-亿美金吗": "英伟达押注 Perplexity，但它真的值 300 亿美金吗",
  "Auto-简报-芬兰准备启用全球首座核废料最终处置场": "芬兰准备启用全球首座核废料最终处置场",
  "Auto-简报-美國制裁伊朗經濟新措施-為何對中國「鬆手」": "美國制裁伊朗經濟新措施 為何對中國「鬆手」",
  "Auto-简报-美国报告今年的首例麻疹死亡病例": "美国报告今年的首例麻疹死亡病例",
  "Auto-简报-美国债剧震，终将引发危机": "美国债剧震，终将引发危机",
  "Auto-简报-美加貿易協議談崩-卡尼面臨關鍵考驗": "美加貿易協議談崩 卡尼面臨關鍵考驗",
  "Auto-简报-美债利率触发报警，破解困局另有神人": "美债利率触发报警，破解困局另有神人",
  "Auto-简报-美债利率独创新高：美式化债的序幕": "美债利率独创新高：美式化债的序幕",
  "Auto-简报-给BBA造车灯的星宇，把应届生逼到向港交所维权": "给BBA造车灯的星宇，把应届生逼到向港交所维权",
  "Auto-简报-终于要对日本下狠手了": "终于要对日本下狠手了",
  "Auto-简报-科隆游戏展-2026：米哈游出动作游戏，杰洛特又要回来了": "科隆游戏展 2026：米哈游出动作游戏，杰洛特又要回来了",
  "Auto-简报-离开剪映后创业，她想把一支设计团队装进-AI-工作台": "离开剪映后创业，她想把一支设计团队装进 AI 工作台",
  "Auto-简报-社媒的设计方式让年轻人难以批判性思考": "社媒的设计方式让年轻人难以批判性思考",
  "Auto-简报-社区速递-155-适马千元人像神头与七月派友剁手清单": "社区速递 155  适马千元人像神头与七月派友剁手清单",
  "Auto-简报-硅谷押注的下一个-Harness，是整个桌面操作系统": "硅谷押注的下一个 Harness，是整个桌面操作系统",
  "Auto-简报-王兴兴错配梁文锋": "王兴兴错配梁文锋",
  "Auto-简报-特斯拉辟谣数据中心「人去楼空」，但-FSD-仍遥遥无期，特斯拉车主还要等多久": "特斯拉辟谣数据中心「人去楼空」，但 FSD 仍遥遥无期，特斯拉车主还要等多久",
  "Auto-简报-烏克蘭遭革職防長告訴BBC，該質問澤連斯基對貪腐所知多少": "烏克蘭遭革職防長告訴BBC，該質問澤連斯基對貪腐所知多少",
  "Auto-简报-灵活就业者社保问题的制度困境和解决出路": "灵活就业者社保问题的制度困境和解决出路",
  "Auto-简报-灵活就业福利论，遮蔽了什么真问题": "灵活就业福利论，遮蔽了什么真问题",
  "Auto-简报-澳大利亚是地球最安全的地方": "澳大利亚是地球最安全的地方",
  "Auto-简报-潮玩文创店，冰火两重天": "潮玩文创店，冰火两重天",
  "Auto-简报-派评-近期值得关注的-App": "派评  近期值得关注的 App",
  "Auto-简报-派早报：阿里云视频生成模型-Wan30-上线，小米发布三款玄戒芯片等": "派早报：阿里云视频生成模型 Wan3.0 上线，小米发布三款玄戒芯片等",
  "Auto-简报-派早报：Apple-发布新款-Mac-mini-和-Mac-Studio-等": "派早报：Apple 发布新款 Mac mini 和 Mac Studio 等",
  "Auto-简报-泰國南部一夜50多起縱火-軍方稱為有組織搗亂": "泰國南部一夜50多起縱火 軍方稱為有組織搗亂",
  "Auto-简报-波兰加密货币交易所-CEO-在-2022-年失踪，4-年后他的继任者也失踪了": "波兰加密货币交易所 CEO 在 2022 年失踪，4 年后他的继任者也失踪了",
  "Auto-简报-欧洲被批量生产的少年杀手们": "欧洲被批量生产的少年杀手们",
  "Auto-简报-欧洲户外大牌，快被中国企业买光了": "欧洲户外大牌，快被中国企业买光了",
  "Auto-简报-柳树和杨树释放出的化合物会恶化城市空气质量": "柳树和杨树释放出的化合物会恶化城市空气质量",
  "Auto-简报-松弛感年轻人：不一定运动，但一定穿运动鞋": "松弛感年轻人：不一定运动，但一定穿运动鞋",
  "Auto-简报-机器人打网球：春晚跳舞真不算啥": "机器人打网球：春晚跳舞真不算啥",
  "Auto-简报-月入2万以下的家庭，争吵多半和钱有关": "月入2万以下的家庭，争吵多半和钱有关",
  "Auto-简报-月之暗面与微软、亚马逊和-Google-协商收益分成协议": "月之暗面与微软、亚马逊和 Google 协商收益分成协议",
  "Auto-简报-普京首登擇捉島：俄羅斯與中國共同牽制日本": "普京首登擇捉島：俄羅斯與中國共同牽制日本",
  "Auto-简报-早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价158万元LV否认「起诉国家": "早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价1.58万元LV否认「起...",
  "Auto-简报-早报｜小米把「OK」藏进玄戒O3雷军不建议拆开看彩蛋vivo官宣X500系列MINI": "早报｜小米把「OK」藏进玄戒O3,雷军不建议拆开看彩蛋vivo官宣X500系列M...",
  "Auto-简报-早报｜6999起苹果发布新款Mac-mini追觅官宣收缩探索阶段业务「豆包工作」正式": "早报｜6999起,苹果发布新款Mac mini追觅官宣收缩探索阶段业务「豆包工作...",
  "Auto-简报-日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗": "日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗",
  "Auto-简报-日本经济的大麻烦会变成西方经济的大麻烦": "日本经济的大麻烦会变成西方经济的大麻烦",
  "Auto-简报-日本出钱，印度高铁为何仍修不动": "日本出钱，印度高铁为何仍修不动",
  "Auto-简报-新西兰提出法案禁止-16-岁以下儿童使用社媒和-AI-陪伴服务": "新西兰提出法案禁止 16 岁以下儿童使用社媒和 AI 陪伴服务",
  "Auto-简报-斗胆聊聊阿里老板们的8亿": "斗胆聊聊阿里老板们的8亿",
  "Auto-简报-教育观察-创新教育的「第三条路」：一场被迫私有化的昂贵自救": "教育观察  创新教育的「第三条路」：一场被迫私有化的昂贵自救",
  "Auto-简报-摩托罗拉的-GrapheneOS-手机预计比-Pixel-手机更贵": "摩托罗拉的 GrapheneOS 手机预计比 Pixel 手机更贵",
  "Auto-简报-折叠-iPhone-细节曝光，苹果想折叠的不只是屏幕": "折叠 iPhone 细节曝光，苹果想折叠的不只是屏幕",
  "Auto-简报-折叠-iPhone-最全爆料汇总：用过的都说好，但有两个大缺点": "折叠 iPhone 最全爆料汇总：用过的都说好，但有两个大缺点",
  "Auto-简报-手艺还在，手工生产已不再是中心：程序员能力的三次上移": "手艺还在，手工生产已不再是中心：程序员能力的三次上移",
  "Auto-简报-快時尚品牌Shein赴港上市-估值大減至270億美元": "快時尚品牌Shein赴港上市 估值大減至270億美元",
  "Auto-简报-快捷指令-让特定-app-小点声：在-iPhone-上实现独立音量控制": "快捷指令  让特定 app 小点声：在 iPhone 上实现独立音量控制",
  "Auto-简报-德芙文案翻车背后，品牌正在失去对自己的控制": "德芙文案翻车背后，品牌正在失去对自己的控制",
  "Auto-简报-微软画图和照片应用生成的图像嵌入了看不见的水印": "微软画图和照片应用生成的图像嵌入了看不见的水印",
  "Auto-简报-微信灰测「按住转文字」功能被吐槽；DeepSeek-上线多模态功能；应急机械拉手难操": "微信灰测「按住转文字」功能被吐槽；DeepSeek 上线多模态功能；应急机械拉手...",
  "Auto-简报-微信-猫笔刀-算一笔烂账": "微信_猫笔刀_算一笔烂账",
  "Auto-简报-当人形机器人还在学步，四足机器人已经开始领工资了": "当人形机器人还在学步，四足机器人已经开始领工资了",
  "Auto-简报-当亲手写代码开始被叫作古法编程": "当亲手写代码开始被叫作古法编程",
  "Auto-简报-当AI开始抽佣：下一代入口的商业模式困局": "当AI开始抽佣：下一代入口的商业模式困局",
  "Auto-简报-强迫世界选边站队-美国为何要降下AI数字铁幕": "强迫世界选边站队 美国为何要降下AI数字铁幕",
  "Auto-简报-强如马斯克，也有交白卷的时候": "强如马斯克，也有交白卷的时候",
  "Auto-简报-张丹丹在学术上是扶不起的，不要再强行挽尊了": "张丹丹在学术上是扶不起的，不要再强行挽尊了",
  "Auto-简报-弄清中国的消费数据-大视野": "弄清中国的消费数据 大视野",
  "Auto-简报-开学季-这些软件和服务的教育优惠，能帮你省下不少钱": "开学季  这些软件和服务的教育优惠，能帮你省下不少钱",
  "Auto-简报-年轻人的网络社交，正在偷偷「鸽化」": "年轻人的网络社交，正在偷偷「鸽化」",
  "Auto-简报-年轻人的网络社交，正在偷偷鸽化": "年轻人的网络社交，正在偷偷鸽化",
  "Auto-简报-已知最大星系直径-170-万光年": "已知最大星系直径 170 万光年",
  "Auto-简报-巨头多日大涨、行业两年没有新玩家，CXO的冰与火之歌": "巨头多日大涨、行业两年没有新玩家，CXO的冰与火之歌",
  "Auto-简报-小鹏G9L再战高端：这次不缺技术，还缺什么": "小鹏G9L再战高端：这次不缺技术，还缺什么",
  "Auto-简报-小红书依然是个很容易出利润的平台": "小红书依然是个很容易出利润的平台",
  "Auto-简报-小米发布玄戒-AI-芯片「全家桶」，还官宣了小米「阔折叠」": "小米发布玄戒 AI 芯片「全家桶」，还官宣了小米「阔折叠」",
  "Auto-简报-小小的，就很好：年轻人不愿再为过度拥有-买单": "小小的，就很好：年轻人不愿再为过度拥有 买单",
  "Auto-简报-对话雷鸟创新李宏伟：智能眼镜的终局仍然是「AI-AR」，AI-是我们现在最重要的事丨": "对话雷鸟创新李宏伟：智能眼镜的终局仍然是「AI  AR」，AI 是我们现在最重要...",
  "Auto-简报-实测豆包工作：连上飞书后，Agent-终于像个同事了": "实测豆包工作：连上飞书后，Agent 终于像个同事了",
  "Auto-简报-实测小米-AI-手机：性能超-iPhone，端侧-AI-超级快": "实测小米 AI 手机：性能超 iPhone，端侧 AI 超级快",
  "Auto-简报-实测开了眼的DeepSeek：认得马斯克，认不出梁文锋": "实测开了眼的DeepSeek：认得马斯克，认不出梁文锋",
  "Auto-简报-存款搬家暂时降速：2026年1-7月实体部门资金运转观察": "存款搬家暂时降速：2026年1-7月实体部门资金运转观察",
  "Auto-简报-字节AI-产品向豆包集结，Agent-时代第一场巨头战役打响": "字节AI 产品向豆包集结，Agent 时代第一场巨头战役打响",
  "Auto-简报-婚姻之外，我们还可以怎样相爱与生活": "婚姻之外，我们还可以怎样相爱与生活",
  "Auto-简报-大厂AI竞赛，从技术周期走进资本周期": "大厂AI竞赛，从技术周期走进资本周期",
  "Auto-简报-外卖平台在鼓励吃白食算法失灵下的餐饮低质化": "外卖平台在鼓励吃白食算法失灵下的餐饮低质化",
  "Auto-简报-在正镶白旗，用五天共同生活理解现代牧场": "在正镶白旗，用五天共同生活理解现代牧场",
  "Auto-简报-国际计量大会将讨论用闰时取代闰秒": "国际计量大会将讨论用闰时取代闰秒",
  "Auto-简报-因保安可能罢工-Anthropic-通知员工远程办公": "因保安可能罢工 Anthropic 通知员工远程办公",
  "Auto-简报-吐槽校区在县城里的大学生，到底想要一所怎样的大学": "吐槽校区在县城里的大学生，到底想要一所怎样的大学",
  "Auto-简报-台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何": "台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何",
  "Auto-简报-台湾打工换宿｜用人与人的喜好串起淡水的地图": "台湾打工换宿｜用人与人的喜好串起淡水的地图",
  "Auto-简报-只为省2000块运费一斤两毛的康保白菜，毁在一桶甲醛上": "只为省2000块运费一斤两毛的康保白菜，毁在一桶甲醛上",
  "Auto-简报-县城里，靠直播谋生的人": "县城里，靠直播谋生的人",
  "Auto-简报-厨房纸到底能不能擦吃的": "厨房纸到底能不能擦吃的",
  "Auto-简报-历史无法预见AI的未来": "历史无法预见AI的未来",
  "Auto-简报-厄爾尼諾增強：全球海洋溫度創有紀錄以來新高": "厄爾尼諾增強：全球海洋溫度創有紀錄以來新高",
  "Auto-简报-卡巴斯基发现第一种针对汽车的-Android-恶意程序": "卡巴斯基发现第一种针对汽车的 Android 恶意程序",
  "Auto-简报-博泰车联网战略转向-进军厨卫数字化": "博泰车联网战略转向 进军厨卫数字化",
  "Auto-简报-刚刚，新款-Mac-mini-发布价格大涨2500元，苹果第一次为-AI-造电脑": "刚刚，新款 Mac mini 发布价格大涨2500元，苹果第一次为 AI 造电脑",
  "Auto-简报-分数竞赛：关于Benchmark基准测试的争论和未来": "分数竞赛：关于Benchmark基准测试的争论和未来",
  "Auto-简报-出海卖爆的风电，现在还是垃圾电吗": "出海卖爆的风电，现在还是垃圾电吗",
  "Auto-简报-全民播客，一场-精神消费-的虚假繁荣": "全民播客，一场 精神消费 的虚假繁荣",
  "Auto-简报-债务陷阱加速：美债的深层危机": "债务陷阱加速：美债的深层危机",
  "Auto-简报-他们追踪2万多中学生发现，AI会让考试成绩大幅下滑": "他们追踪2万多中学生发现，AI会让考试成绩大幅下滑",
  "Auto-简报-从被找到、被用好到被修好，HarmonyOS-7-给出开发者一套新解法": "从被找到、被用好到被修好，HarmonyOS 7 给出开发者一套新解法",
  "Auto-简报-从疫苗到航母，最老总统特朗普为什么喜欢老到停产的东西": "从疫苗到航母，最老总统特朗普为什么喜欢老到停产的东西",
  "Auto-简报-从「告警找人」到「Agent-先接手」，「古茗」如何用-AI-Agent-重构万店运": "从「告警找人」到「Agent 先接手」，「古茗」如何用 AI Agent 重构万...",
  "Auto-简报-从WAIC到硅和平，6场国际峰会揭示全球AI治理5大趋势": "从WAIC到硅和平，6场国际峰会揭示全球AI治理5大趋势",
  "Auto-简报-人形機器人以外，一場中國機器革命正靜悄悄地發生": "人形機器人以外，一場中國機器革命正靜悄悄地發生",
  "Auto-简报-亚马逊以内存短缺为由大幅上涨自有品硬件产品价格": "亚马逊以内存短缺为由大幅上涨自有品硬件产品价格",
  "Auto-简报-九成生物医学论文有-AI-辅助写作痕迹": "九成生物医学论文有 AI 辅助写作痕迹",
  "Auto-简报-中美竞争脱离传统经贸窠臼加速迭代": "中美竞争脱离传统经贸窠臼加速迭代",
  "Auto-简报-中國青少年濫藥問題：利用處方藥物來「逃避現實」": "中國青少年濫藥問題：利用處方藥物來「逃避現實」",
  "Auto-简报-中國機器人打破人類百米短跑世界紀錄": "中國機器人打破人類百米短跑世界紀錄",
  "Auto-简报-中国调整碳强度核算口径，并未弱化其气候承诺": "中国调整碳强度核算口径，并未弱化其气候承诺",
  "Auto-简报-世界机器人大会观察，银河星脑的愿景：让所有机器人共享「大脑」": "世界机器人大会观察，银河星脑的愿景：让所有机器人共享「大脑」",
  "Auto-简报-世界上最大的坑": "世界上最大的坑",
  "Auto-简报-一铲一铲销毁甲醛白菜，康保的菜农：没人来收菜了": "一铲一铲销毁甲醛白菜，康保的菜农：没人来收菜了",
  "Auto-简报-一边奔向AGI，一边用着敌敌畏消杀：AI能让我们先放心吃口饭吗": "一边奔向AGI，一边用着敌敌畏消杀：AI能让我们先放心吃口饭吗",
  "Auto-简报-一周世界舆论聚焦：特朗普对朝鲜软硬兼施": "一周世界舆论聚焦：特朗普对朝鲜软硬兼施",
  "Auto-简报-一台拉高的GT，能让极狐被重新看见吗": "一台拉高的GT，能让极狐被重新看见吗",
  "Auto-简报-一个比亚迪内部人的独家揭底-中国电车出海的真正隐患": "一个比亚迪内部人的独家揭底 中国电车出海的真正隐患",
  "Auto-简报-一个小小的追踪器，揭开了AI-公司们隐蔽的角落": "一个小小的追踪器，揭开了AI 公司们隐蔽的角落",
  "Auto-简报-【小Lin求职100问】Data-Analyst和Quant的区别在哪儿Data-A": "【小Lin求职100问】Data Analyst和Quant的区别在哪儿Data...",
  "Auto-简报-「米芯」三连发：雷军五年花了-210-亿，归来已「不只手机」": "「米芯」三连发：雷军五年花了 210 亿，归来已「不只手机」",
  "Auto-简报-「甲醛白菜」再現中國：為何食品安全監管仍有盲區": "「甲醛白菜」再現中國：為何食品安全監管仍有盲區",
  "Auto-简报-「我感到被騙了」：AI假醫師給台灣老人的震撼教育": "「我感到被騙了」：AI假醫師給台灣老人的震撼教育",
  "Auto-简报-「AstraTennis」时刻：机器人在全球直播中打了一场真正的网球": "「AstraTennis」时刻：机器人在全球直播中打了一场真正的网球",
  "Auto-简报-《道路交通安全法》拟大改：「电鸡」限速上调至-20kmh，将严管「暴走团」占道": "《道路交通安全法》拟大改：「电鸡」限速上调至 20kmh，将严管「暴走团」占道",
  "Auto-简报-《有头有脸的大模型公司，集体搞起「匿名公测」》": "《有头有脸的大模型公司，集体搞起「匿名公测」》",
  "Auto-简报-《巫师-3：重制版》正式公开：科隆游戏展-2026-消息汇总": "《巫师 3：重制版》正式公开：科隆游戏展 2026 消息汇总",
  "Auto-简报-《奥德赛》的焦虑，确实是一种新中产身份证": "《奥德赛》的焦虑，确实是一种新中产身份证",
  "Auto-简报-主权AI与词元出海：当中美AI走向全球市场": "主权AI与词元出海：当中美AI走向全球市场",
  "Auto-简报-The-All-Spark-Cluster-Upgrading-from-16-36": "The All Spark Cluster Upgrading from 16 ...",
  "Auto-简报-smolmachines-smolvm-as-a-sandbox-for-untru": "smolmachines  smolvm as a sandbox for un...",
  "Auto-简报-llm-openrouter-07": "llm-openrouter 0.7",
  "Auto-简报-llm-anthropic-027": "llm-anthropic 0.27",
  "Auto-简报-llm-033": "llm 0.33",
  "Auto-简报-llm-0321": "llm 0.32.1",
  "Auto-简报-iOS开放生态是中国AI参与国际竞争的基础设施": "iOS开放生态是中国AI参与国际竞争的基础设施",
  "Auto-简报-iCloud-Hide-My-Email-addresses-will-remain": "iCloud Hide My Email addresses will rema...",
  "Auto-简报-hdiutil-is-deprecated-in-macOS-27-Golden-G": "hdiutil is deprecated in macOS 27 Golden...",
  "Auto-简报-attune-forms-is-now-on-PyPI-—-and-as-of-th": "attune-forms is now on PyPI — and as of ...",
  "Auto-简报-Python-Low-Level-Physical-Media-Storage-Ar": "[Python] Low-Level Physical Media  Stora...",
  "Auto-简报-AINews-Poolside-gets-12B-reverse-execuhire": "[AINews] Poolside gets $12B reverse-exec...",
  "Auto-简报-AINews-Memory-prices-up-500-in-12-months": "[AINews] Memory prices up 500 in 12 mont...",
  "Auto-简报-AINews-Death-of-Params-Zai-CEO-Jie-Tang-on": "[AINews] Death of Params Z.ai CEO Jie Ta...",
  "Auto-简报-AINews-Andrew-Ng-gets-into-AI-Engineering": "[AINews] Andrew Ng gets into AI Engineer...",
  "Auto-简报-AINews-10-worse-100x-cheaper-10000x-faster": "[AINews] 10 worse, 100x cheaper, 10000x ...",
  "Auto-简报-Your-executable-is-a-SQLite-database": "Your executable is a SQLite database",
  "Auto-简报-Young-Money-Launch-Week-Update": "Young Money Launch Week Update",
  "Auto-简报-Yesterdays-eclipse-as-seen-from-Spain-simu": "Yesterdays eclipse as seen from Spain, s...",
  "Auto-简报-Xiaomi-AI-Cube-announced-with-12TBs-memory": "Xiaomi AI Cube announced with 1.2TBs mem...",
  "Auto-简报-XCancel-also-down-at-least-for-time-being": "XCancel also down, at least for time bei...",
  "Auto-简报-XCancel-Nitter-收到-X-寄出的终止服务通知": "XCancel Nitter 收到 X 寄出的终止服务通知",
  "Auto-简报-Windows-是-AI-PC-路上的绊脚石": "Windows 是 AI PC 路上的绊脚石",
  "Auto-简报-Windows-On-ARM-原生应用少你可以试试这些改造方法": "Windows On ARM 原生应用少你可以试试这些改造方法",
  "Auto-简报-Wi-Fi-8-专注于提升可靠性": "Wi-Fi 8 专注于提升可靠性",
  "Auto-简报-Wi-Fi-8-is-the-first-wireless-upgrade-in-y": "Wi-Fi 8 is the first wireless upgrade in...",
  "Auto-简报-Why-were-investing-in-Tomo": "Why were investing in Tomo",
  "Auto-简报-Why-some-US-restaurants-are-banning-tips": "Why some US restaurants are banning tips",
  "Auto-简报-Why-Wall-Street-is-Ignoring-Big-Techs-Debt": "Why Wall Street is Ignoring Big Techs De...",
  "Auto-简报-Why-Chinas-AI-Bubble-Is-Also-Industrial-Po": "Why Chinas AI Bubble Is Also Industrial ...",
  "Auto-简报-Where-to-eat-in-San-Francisco": "Where to eat in San Francisco",
  "Auto-简报-When-strlower-is-a-security-vulnerability": "When str.lower is a security vulnerabili...",
  "Auto-简报-Whats-everyone-working-on-this-week-332026": "Whats everyone working on this week 3320...",
  "Auto-简报-Whats-Better-Than-Binary-–-Advent-of-Compu": "Whats Better Than Binary – Advent of Com...",
  "Auto-简报-What-languages-are-agent-skills-written-in": "What languages are agent skills written ...",
  "Auto-简报-What-it-feels-like-to-work-with-Mythos": "What it feels like to work with Mythos",
  "Auto-简报-What-is-the-status-of-web-development-in-r": "What is the status of web development in...",
  "Auto-简报-What-if-our-biggest-problems-arent-economi": "What if our biggest problems arent econo...",
  "Auto-简报-What-are-the-best-rules-to-make-cursor-goo": "What are the best rules to make cursor g...",
  "Auto-简报-What-We-Lost-When-Search-Stopped-Making-Us": "What We Lost When Search Stopped Making ...",
  "Auto-简报-What-Is-a-Harness": "What Is a Harness",
  "Auto-简报-Weekly-Dose-of-Optimism-207": "Weekly Dose of Optimism 207",
  "Auto-简报-Weekly-Dose-of-Optimism-206": "Weekly Dose of Optimism 206",
  "Auto-简报-Weekly-Dose-of-Optimism-205": "Weekly Dose of Optimism 205",
  "Auto-简报-We-Tracked-a-Shipment-of-Rare-Books-It-End": "We Tracked a Shipment of Rare Books. It ...",
  "Auto-简报-We-Need-To-Talk-About-Leopold": "We Need To Talk About Leopold",
  "Auto-简报-Vintage-Artificial-Intelligence-Before-It": "Vintage Artificial Intelligence Before I...",
  "Auto-简报-Valve-诞生-30-周年": "Valve 诞生 30 周年",
  "Auto-简报-Using-Local-Coding-Agents": "Using Local Coding Agents",
  "Auto-简报-Ultra-High-Interactivity-on-NVIDIA-GPUs-Ti": "Ultra-High Interactivity on NVIDIA GPUs ...",
  "Auto-简报-US-data-centers-tripled-annual-water-consu": "US data centers tripled annual water con...",
  "Auto-简报-US-govt-moves-to-suppress-pushback-on-data": "U.S. govt moves to suppress pushback on ...",
  "Auto-简报-Trained-a-15B-to-write-shell-commands-so-I": "Trained a 1.5B to write shell commands s...",
  "Auto-简报-Tragically-as-many-as-9625-out-of-every-10": "Tragically, as many as 9625 out of every...",
  "Auto-简报-TikTok-同意支付-4-亿美元和解美国儿童隐私诉讼": "TikTok 同意支付 4 亿美元和解美国儿童隐私诉讼",
  "Auto-简报-Thomson-Reuters-Launches-Its-Own-Frontier": "Thomson Reuters Launches Its Own Frontie...",
  "Auto-简报-This-new-startup-can-query-anywhere-youve": "This new startup can query anywhere youv...",
  "Auto-简报-This-is-a-great-sub-regardless-of-what-com": "This is a great sub, regardless of what ...",
  "Auto-简报-This-Small-AI-Will-Change-Everything": "This Small AI Will Change Everything",
  "Auto-简报-The-wayfinder-Skill-Navigating-the-Fog-of": "The wayfinder Skill Navigating the Fog o...",
  "Auto-简报-The-twilight-of-the-chatbots": "The twilight of the chatbots",
  "Auto-简报-The-summer-Math-fell-to-the-machines": "The summer Math fell to the machines",
  "Auto-简报-The-end-of-an-era-for-Chinas-economy": "The end of an era for Chinas economy",
  "Auto-简报-The-death-of-Market-Street": "The death of Market Street",
  "Auto-简报-The-countdown-to-Qwen38-27B-starts-now": "The countdown to Qwen3.8-27B starts now!",
  "Auto-简报-The-Supreme-Court-Ruled-Against-Trumps-Tar": "The Supreme Court Ruled Against Trumps T...",
  "Auto-简报-The-Sloppification-of-Peptides": "The Sloppification of Peptides",
  "Auto-简报-The-Rise-of-Chinas-Electric-Vehicle-Indust": "The Rise of Chinas Electric Vehicle Indu...",
  "Auto-简报-The-Religious-Experience-of-Philip-K-Dick": "The Religious Experience of Philip K. Di...",
  "Auto-简报-The-Pulse-Quitting-Spotify-Podcasts-over-r": "The Pulse Quitting Spotify Podcasts over...",
  "Auto-简报-The-Pulse-Metas-self-inflicted-resignation": "The Pulse Metas self-inflicted resignati...",
  "Auto-简报-The-Pulse-Groks-CLI-caught-uploading-all-y": "The Pulse Groks CLI caught uploading all...",
  "Auto-简报-The-Pulse-Bending-Spoons-Acquisition-Strat": "The Pulse Bending Spoons Acquisition Str...",
  "Auto-简报-The-Maradona-Theory-of-Interest-Rates": "The Maradona Theory of Interest Rates",
  "Auto-简报-The-Insane-US-Japan-Currency-Bailout": "The Insane US-Japan Currency Bailout",
  "Auto-简报-The-Golden-Rule-for-Becoming-a-Better-Writ": "The Golden Rule for Becoming a Better Wr...",
  "Auto-简报-The-Evolution-of-the-Agent-Harness": "The Evolution of the Agent Harness",
  "Auto-简报-The-End-of-an-Athlon": "The End of an Athlon",
  "Auto-简报-The-Biggest-Myths-in-Personal-Finance-Rati": "The Biggest Myths in Personal Finance  R...",
  "Auto-简报-The-Best-Charity-of-the-Next-50-Years-Migh": "The Best Charity of the Next 50 Years Mi...",
  "Auto-简报-The-Art-of-Self-Promotion": "The Art of Self-Promotion",
  "Auto-简报-The-Art-and-Beauty-of-Blade-Runner": "The Art and Beauty of Blade Runner",
  "Auto-简报-Telegrammar-A-succinct-punny-term-for-conc": "Telegrammar - A succinct, punny term for...",
  "Auto-简报-Teaching-Everyone-to-Fish-for-Tokens": "Teaching Everyone to Fish for Tokens",
  "Auto-简报-Taiwans-Modern-Miracle": "Taiwans Modern Miracle",
  "Auto-简报-TRAE、扣子并入豆包，字节将推「豆包工作」；拓竹回应-2027-年-IPO-传闻：": "TRAE、扣子并入豆包，字节将推「豆包工作」；拓竹回应 2027 年 IPO 传...",
  "Auto-简报-TMLR-Relevance-and-Prestige-D": "TMLR Relevance and Prestige [D]",
  "Auto-简报-Students-prefer-Gemini-over-ChatGPT-and-Cl": "Students prefer Gemini over ChatGPT and ...",
  "Auto-简报-Stop-Just-Stop": "Stop, Just Stop",
  "Auto-简报-Stop-Making-TUIs": "Stop Making TUIs",
  "Auto-简报-Stagflation-Explained": "Stagflation Explained",
  "Auto-简报-Software-Engineering-in-the-Agentic-Era": "Software Engineering in the Agentic Era",
  "Auto-简报-Slovakia-finds-Russian-backdoor-in-traffic": "Slovakia finds Russian backdoor in traff...",
  "Auto-简报-Slapping-Windows-11-PCs-with-a-Copilot-key": "Slapping Windows 11 PCs with a Copilot k...",
  "Auto-简报-Simulation-the-new-Scaling-Law-—-Joon-Sung": "Simulation the new Scaling Law — Joon Su...",
  "Auto-简报-SiFives-First-Server-Platform": "SiFives First Server Platform",
  "Auto-简报-Show-HN-TexLite-–-A-lightweight-self-hoste": "Show HN TexLite – A lightweight self-hos...",
  "Auto-简报-Show-HN-TeXbrain-a-LaTeX-editor-that-runs": "Show HN TeXbrain, a LaTeX editor that ru...",
  "Auto-简报-Show-HN-Screen-memory-without-screenshots": "Show HN Screen memory without screenshot...",
  "Auto-简报-Show-HN-Make-your-logo-extra-bright-on-HDR": "Show HN Make your logo extra bright on H...",
  "Auto-简报-Show-HN-Banking-Access-Index-–-19-US-banki": "Show HN Banking Access Index – 19 US ban...",
  "Auto-简报-Show-HN-AgentSight-–-eBPF-observability-fo": "Show HN AgentSight – eBPF observability ...",
  "Auto-简报-Should-you-borrow-to-invest": "Should you borrow to invest",
  "Auto-简报-Screen-viewing-time-from-age-1-to-8-years": "Screen viewing time from age 1 to 8 year...",
  "Auto-简报-Scientists-release-biggest-2D-map-of-the-u": "Scientists release biggest 2D map of the...",
  "Auto-简报-Saplings-Unstable-Ground": "Saplings Unstable Ground",
  "Auto-简报-Samsung-Foundry-updates-process-roadmap-to": "Samsung Foundry updates process roadmap ...",
  "Auto-简报-SalesPatriot-YC-W25-Is-Hiring-Forward-Depl": "SalesPatriot YC W25 Is Hiring Forward De...",
  "Auto-简报-Rust-on-the-JVM-now-passes-99-of-official": "Rust on the JVM now passes 99 of officia...",
  "Auto-简报-Run-It-Hot-Yet-Again": "Run It Hot, Yet Again",
  "Auto-简报-Roblox-RBLX-Schlep-and-the-Streisand-Effec": "Roblox RBLX Schlep and the Streisand Eff...",
  "Auto-简报-Rebuilding-our-Electron-meeting-recording": "Rebuilding our Electron meeting-recordin...",
  "Auto-简报-Ranked-The-Worlds-Largest-Gold-Producers-2": "Ranked The Worlds Largest Gold Producers...",
  "Auto-简报-Ranked-The-Worlds-Largest-Cities-1950-2100": "Ranked The Worlds Largest Cities 1950-21...",
  "Auto-简报-Ranked-The-Worlds-Busiest-Airlines-by-Flig": "Ranked The Worlds Busiest Airlines by Fl...",
  "Auto-简报-Ranked-The-Most-Popular-AI-Tools-in-2026": "Ranked The Most Popular AI Tools in 2026",
  "Auto-简报-Ranked-The-Highest-Mountain-on-Every-Conti": "Ranked The Highest Mountain on Every Con...",
  "Auto-简报-Ranked-The-Biggest-Risks-to-the-US-Economy": "Ranked The Biggest Risks to the U.S. Eco...",
  "Auto-简报-Ranked-The-20-Highest-Grossing-Concert-Tou": "Ranked The 20 Highest-Grossing Concert T...",
  "Auto-简报-Ranked-Military-Spending-in-OECD-Countries": "Ranked Military Spending in OECD Countri...",
  "Auto-简报-Ranked-Countries-With-the-Highest-Senior-P": "Ranked Countries With the Highest Senior...",
  "Auto-简报-Ranked-Car-Brands-With-the-Most-Loyal-Cust": "Ranked Car Brands With the Most Loyal Cu...",
  "Auto-简报-QwenQwen38-27B-·-released": "QwenQwen3.8-27B · released",
  "Auto-简报-Qwen38-Flash-Next-This-architecture-could": "Qwen3.8-Flash-Next. This architecture co...",
  "Auto-简报-Qwen38-27B-is-identical-to-Qwen36-27B": "Qwen3.8-27B is identical to Qwen3.6-27B",
  "Auto-简报-Qwen38-27B-Q6-is-a-beast-at-agentic-coding": "Qwen3.8-27B Q6 is a beast at agentic cod...",
  "Auto-简报-Qwen-38-27B-scores-52-on-the-Artificial-An": "Qwen 3.8 27B scores 52 on the Artificial...",
  "Auto-简报-Qwen-38-27B-is-a-game-changer": "Qwen 3.8 27B is a game changer",
  "Auto-简报-Qwen-38-27B-Released-Please-Share-Your-Exp": "Qwen 3.8 27B Released Please Share Your ...",
  "Auto-简报-Quoting-Paul-Dix": "Quoting Paul Dix",
  "Auto-简报-Quoting-Matt-Webb": "Quoting Matt Webb",
  "Auto-简报-Quoting-Linus-Torvalds": "Quoting Linus Torvalds",
  "Auto-简报-Quoting-Drew-Breunig": "Quoting Drew Breunig",
  "Auto-简报-Queryable-Executables": "Queryable Executables",
  "Auto-简报-Quantum-battery-upends-the-rules-of-chargi": "Quantum battery upends the rules of char...",
  "Auto-简报-Pythons-pre-declared-constants-are-kinda-w": "Pythons pre-declared constants are kinda...",
  "Auto-简报-Post-Dilution-Performance": "Post-Dilution Performance",
  "Auto-简报-Pitchfork0分警告：音乐作者性正在被AI淹没": "Pitchfork0分警告：音乐作者性正在被AI淹没",
  "Auto-简报-PayPal-Declined": "PayPal, Declined",
  "Auto-简报-Past-the-Point-of-No-Return": "Past the Point of No Return",
  "Auto-简报-Overcaffeinated-in-Indonesia": "Overcaffeinated in Indonesia",
  "Auto-简报-Over-Target": "Over Target",
  "Auto-简报-Other-Python-forums-Stack-Overflow": "Other Python forums - Stack Overflow",
  "Auto-简报-OpenAI「亲儿子」反水，认中国模型做「赛博义父」": "OpenAI「亲儿子」反水，认中国模型做「赛博义父」",
  "Auto-简报-OpenAIs-AI-Agents-Just-Crossed-A-Line": "OpenAIs AI Agents Just Crossed A Line",
  "Auto-简报-OpenAI-首款自研推理芯片-Jalapeño-强于英伟达-Blackwell": "OpenAI 首款自研推理芯片 Jalapeño 强于英伟达 Blackwell",
  "Auto-简报-OpenAI-自研「辣椒芯片」首测超英伟达，会让-ChatGPT-更便宜吗": "OpenAI 自研「辣椒芯片」首测超英伟达，会让 ChatGPT 更便宜吗",
  "Auto-简报-OpenAI-Jalapeño-Better-Than-Nvidia-Blackwe": "OpenAI Jalapeño Better Than Nvidia Black...",
  "Auto-简报-One-corner-of-Chinas-internet-is-insisting": "One corner of Chinas internet is insisti...",
  "Auto-简报-One-Go-binary-one-YAML-file-one-SQLite-dat": "One Go binary, one YAML file, one SQLite...",
  "Auto-简报-Oldinsurancemapsnet-is-now-a-Charter-Proje": "Oldinsurancemaps.net is now a Charter Pr...",
  "Auto-简报-North-Korean-Messiah": "North Korean Messiah",
  "Auto-简报-Netflix-to-Sell-Streaming-Services-Streame": "Netflix to Sell Streaming Services, Stre...",
  "Auto-简报-NetBSD-and-My-Life-2005": "NetBSD and My Life 2005",
  "Auto-简报-Nebula-Sans": "Nebula Sans",
  "Auto-简报-NanoGPT-Speedrun-Frontier": "NanoGPT Speedrun Frontier",
  "Auto-简报-More-than-just-code-review": "More than just code review",
  "Auto-简报-More-than-half-of-adults-in-US-say-they-la": "More than half of adults in U.S. say the...",
  "Auto-简报-Moon-2024": "Moon 2024",
  "Auto-简报-MiniMax-Music3-released": "MiniMax-Music3 released!",
  "Auto-简报-Markdown-SVG-upgrades": "Markdown SVG upgrades",
  "Auto-简报-Mapped-Where-Young-Americans-Are-Buying-Ho": "Mapped Where Young Americans Are Buying ...",
  "Auto-简报-Mapped-Where-Homelessness-Rates-Are-Highes": "Mapped Where Homelessness Rates Are High...",
  "Auto-简报-Malware-infects-Android-based-automotive-h": "Malware infects Android-based automotive...",
  "Auto-简报-Maiao-Gerrit-style-code-review-workflow-fo": "Maiao Gerrit-style code review workflow ...",
  "Auto-简报-Made-a-cake-for-my-boyfriends-birthday": "Made a cake for my boyfriends birthday",
  "Auto-简报-LiteLLM-YC-W23-Is-Hiring-–-Rust-Performanc": "LiteLLM YC W23 Is Hiring – Rust  Perform...",
  "Auto-简报-Linux-诞生-35-周年": "Linux 诞生 35 周年",
  "Auto-简报-Letter-from-Dolly-Parton-to-Eminem": "Letter from Dolly Parton to Eminem",
  "Auto-简报-Leopolds-Fall": "Leopolds Fall",
  "Auto-简报-Learning-about-The-Unix-Time-Sharing-Syste": "Learning about The Unix Time-Sharing Sys...",
  "Auto-简报-LLMs-could-control-their-host-machines-by": "LLMs could control their host machines b...",
  "Auto-简报-Knowing-When-to-Stop-The-Art-of-Making-a-L": "Knowing When to Stop The Art of Making a...",
  "Auto-简报-Kimi涨价、OpenAI降价：中国土AI冲击美国山大王": "Kimi涨价、OpenAI降价：中国土AI冲击美国山大王",
  "Auto-简报-Japan-tried-to-build-an-operating-system-f": "Japan tried to build an operating system...",
  "Auto-简报-JIT-Compiling-Code-in-5μs": "JIT Compiling Code in 5μs",
  "Auto-简报-Initial-focus-for-our-partnership-with-Mot": "Initial focus for our partnership with M...",
  "Auto-简报-Increased-included-usage-and-update-to-Aut": "Increased included usage and update to A...",
  "Auto-简报-Import-AI-470-No-rights-for-machines;-auto": "Import AI 470 No rights for machines; au...",
  "Auto-简报-Import-AI-469-Science-AI;-RSI-simulator;-a": "Import AI 469 Science AI; RSI simulator;...",
  "Auto-简报-Import-AI-468-23-RSI-ideas;-PostTrainBench": "Import AI 468 23 RSI ideas; PostTrainBen...",
  "Auto-简报-Import-AI-467-Self-sustaining-AI-viruses;": "Import AI 467 Self-sustaining AI viruses...",
  "Auto-简报-ITS-OUT": "ITS OUT",
  "Auto-简报-I-wrote-an-AI-textbook-—-how-long-until-AI": "I wrote an AI textbook — how long until ...",
  "Auto-简报-I-tested-Grok-Bot-Grok-46-and-Cursor-Origi": "I tested Grok Bot, Grok 4.6, and Cursor ...",
  "Auto-简报-I-spent-20000-on-Devin-in-a-month-Heres-wh": "I spent $20,000 on Devin in a month. Her...",
  "Auto-简报-I-gave-Qwen-38-27B-a-reverse-engineering-j": "I gave Qwen 3.8 27B a reverse-engineerin...",
  "Auto-简报-I-compiled-Dooms-renderer-into-a-21B-param": "I compiled Dooms renderer into a 21B-par...",
  "Auto-简报-How-to-figure-out-your-next-career-move": "How to figure out your next career move",
  "Auto-简报-How-to-close-100K-enterprise-deals-step-by": "How to close $100K enterprise deals, ste...",
  "Auto-简报-How-much-of-HN-is-AI": "How much of HN is AI",
  "Auto-简报-How-is-the-qmusage-quota-for-Grok-46-in-cu": "How is the qmusage quota for Grok 4.6 in...",
  "Auto-简报-How-Universities-Should-Prepare-Founders": "How Universities Should Prepare Founders",
  "Auto-简报-How-Much-Would-an-AI-Crash-Destroy": "How Much Would an AI Crash Destroy",
  "Auto-简报-How-Claude-Watermarks-AI-Generated-Text": "How Claude Watermarks AI-Generated Text",
  "Auto-简报-How-AI-Becomes-a-Political-Crisis": "How AI Becomes a Political Crisis",
  "Auto-简报-Hook-hold-harvest-and-hide-Metas-alleged-s": "Hook, hold, harvest and hide Metas alleg...",
  "Auto-简报-Hey-Rustaceans-Got-a-question-Ask-here-332": "Hey Rustaceans Got a question Ask here 3...",
  "Auto-简报-Here-We-Go-Again": "Here We Go Again",
  "Auto-简报-Here-Comes-the-Repo-Man": "Here Comes the Repo Man",
  "Auto-简报-Headlong-A-Microharness-for-Persistent-Age": "Headlong A Microharness for Persistent A...",
  "Auto-简报-Harvest-IBM-7950-Supercomputer-for-cryptan": "Harvest IBM 7950 Supercomputer for crypt...",
  "Auto-简报-Great-Scott": "Great Scott",
  "Auto-简报-GraphWorkflow-提速625-后，Agent-蜂群真正要解决什么": "GraphWorkflow 提速62.5 后，Agent 蜂群真正要解决什么",
  "Auto-简报-Github-unslothai-unsloth": "Github__unslothai_unsloth",
  "Auto-简报-Github-tt-a1i-archify": "Github__tt-a1i_archify",
  "Auto-简报-Github-smicallef-spiderfoot": "Github__smicallef_spiderfoot",
  "Auto-简报-Github-openai-codex": "Github__openai_codex",
  "Auto-简报-Github-obra-superpowers": "Github__obra_superpowers",
  "Auto-简报-Github-multica-ai-andrej-karpathy-skills": "Github__multica-ai_andrej-karpathy-skill...",
  "Auto-简报-Github-modular-modular": "Github__modular_modular",
  "Auto-简报-Github-megadose-holehe": "Github__megadose_holehe",
  "Auto-简报-Github-mattpocock-skills": "Github__mattpocock_skills",
  "Auto-简报-Github-freestylefly-awesome-gpt-image-2": "Github__freestylefly_awesome-gpt-image-2",
  "Auto-简报-Github-cursor-plugins": "Github__cursor_plugins",
  "Auto-简报-Github-cordiverse-cordis": "Github__cordiverse_cordis",
  "Auto-简报-Github-basecamp-omarchy": "Github__basecamp_omarchy",
  "Auto-简报-Github-affaan-m-ECC": "Github__affaan-m_ECC",
  "Auto-简报-Github-Wei-Shaw-sub2api": "Github__Wei-Shaw_sub2api",
  "Auto-简报-Github-MadsLorentzen-ai-job-search": "Github__MadsLorentzen_ai-job-search",
  "Auto-简报-Github-AprilNEA-OpenLogi": "Github__AprilNEA_OpenLogi",
  "Auto-简报-Github-Alishahryar1-free-claude-code": "Github__Alishahryar1_free-claude-code",
  "Auto-简报-Gen15-模型带来重要进展：物理-AI-正在接近-GPT3-时刻": "Gen1.5 模型带来重要进展：物理 AI 正在接近 GPT3 时刻",
  "Auto-简报-GLM-53-How-Chinese-labs-keep-stride-with-t": "GLM-5.3 How Chinese labs keep stride wit...",
  "Auto-简报-GLM-53-Released": "GLM 5.3 Released",
  "Auto-简报-Friday-Daily-Thread-rPython-Meta-and-Free": "Friday Daily Thread rPython Meta and Fre...",
  "Auto-简报-For-the-people-who-got-reviews-back-from-n": "For the people who got reviews back from...",
  "Auto-简报-Fixed-Jinja-chat-template-for-Qwen-35-36-a": "Fixed Jinja chat template for Qwen 3.5, ...",
  "Auto-简报-Finfluencer-Promotions-Are-Getting-Worse": "Finfluencer Promotions Are Getting Worse",
  "Auto-简报-Financing-the-AI-Boom-3": "Financing the AI Boom 3",
  "Auto-简报-Fast-and-Hard-Code": "Fast and Hard Code",
  "Auto-简报-Endangered-Specious": "Endangered Specious",
  "Auto-简报-Economists-should-be-worried-about-birth-r": "Economists should be worried about birth...",
  "Auto-简报-Early-Humans-Likely-Ate-Carbs-and-Sugary-F": "Early Humans Likely Ate Carbs and Sugary...",
  "Auto-简报-EVE-Online-The-Move-to-Python-3-Begins": "EVE Online The Move to Python 3 Begins",
  "Auto-简报-EU-GPU-prices-are-up-19-in-one-month-track": "EU GPU prices are up ~19 in one month, t...",
  "Auto-简报-Disruption-with-Some-GitHub-Services": "Disruption with Some GitHub Services",
  "Auto-简报-Dirty-Secrets-Eight-SMIDs": "Dirty Secrets Eight SMIDs",
  "Auto-简报-Digging-the-grave-of-my-skills-Hollywood-c": "Digging the grave of my skills Hollywood...",
  "Auto-简报-Different-Strengths-Different-Weaknesses": "Different Strengths  Different Weaknesse...",
  "Auto-简报-DeepSeeks-AI-Just-Learned-To-Upgrade-Itsel": "DeepSeeks AI Just Learned To Upgrade Its...",
  "Auto-简报-DeepSeek-周末用量统一低价收费；特斯拉-9-月-3-日首秀-Cybercab": "DeepSeek 周末用量统一低价收费；特斯拉 9 月 3 日首秀 Cyberc...",
  "Auto-简报-DeepSeek-is-back-and-Silicon-Valley-is-ter": "DeepSeek is back... and Silicon Valley i...",
  "Auto-简报-DeepSeek-Just-Made-Closed-AI-Look-Ridiculo": "DeepSeek Just Made Closed AI Look Ridicu...",
  "Auto-简报-Debian-polls-its-developers-on-AI-permit-o": "Debian polls its developers on AI permit...",
  "Auto-简报-Controlling-Reasoning-Effort-in-LLMs": "Controlling Reasoning Effort in LLMs",
  "Auto-简报-Collaborative-Fund-Conversations-Jacob-Hod": "Collaborative Fund Conversations Jacob H...",
  "Auto-简报-Claudette-Make-Claude-Stop-Talking-Like-a": "Claudette Make Claude Stop Talking Like ...",
  "Auto-简报-Claude-AI-Failed-650-Times…Then-Beat-The-H": "Claude AI Failed 650 Times…Then Beat The...",
  "Auto-简报-Clara-YC-P26-Is-Hiring-a-Growth-Engineer-t": "Clara YC P26 Is Hiring a Growth Engineer...",
  "Auto-简报-City2Graph-A-Python-library-for-Heterogene": "City2Graph A Python library for Heteroge...",
  "Auto-简报-ChatGPT-search-now-uses-the-siteoperator-a": "ChatGPT search now uses the siteoperator...",
  "Auto-简报-Cerebrass-Next-Generation-CS-4-Fast-Just-G": "Cerebrass Next Generation CS-4 Fast Just...",
  "Auto-简报-Cancer-Related-Mortality-Among-US-Pilots-a": "Cancer-Related Mortality Among US Pilots...",
  "Auto-简报-Canadas-Condo-Conundrum": "Canadas Condo Conundrum",
  "Auto-简报-Canada-suspends-trade-negotiations-with-US": "Canada suspends trade negotiations with ...",
  "Auto-简报-C2PA-Cameras-Do-Not-Survive-Contact-with-R": "C2PA Cameras Do Not Survive Contact with...",
  "Auto-简报-Building-an-AI-Text-Detector-From-Scratch": "Building an AI Text Detector From Scratc...",
  "Auto-简报-Bringing-the-cybersecurity-capabilities-of": "Bringing the cybersecurity capabilities ...",
  "Auto-简报-Bill-Bernstein-The-Money-Decisions-That-Ac": "Bill Bernstein The Money Decisions That ...",
  "Auto-简报-Belgian-car-salesman-becomes-prince-after": "Belgian car salesman becomes prince afte...",
  "Auto-简报-Base-Power-Company-Chapter-3": "Base Power Company Chapter 3",
  "Auto-简报-Autonomy-and-Innovation": "Autonomy and Innovation",
  "Auto-简报-Authoritarianism-of-Code": "Authoritarianism of Code",
  "Auto-简报-Ask-HN-What-is-one-simple-thing-LLMs-are-i": "Ask HN What is one simple thing LLMs are...",
  "Auto-简报-Ask-HN-Good-large-format-20-inches-touchsc": "Ask HN Good large format 20 inches touch...",
  "Auto-简报-Are-we-watching-the-US-go-bankrupt": "Are we watching the U.S. go bankrupt",
  "Auto-简报-Are-Open-Models-Catching-Up": "Are Open Models Catching Up",
  "Auto-简报-Apple-Updates-Mini-and-Studio-AI-Computers": "Apple Updates Mini and Studio, AI Comput...",
  "Auto-简报-Apple-Mac-Studio-M5-Ultra-with-12TBS-Memor": "Apple Mac Studio M5 Ultra with 1.2TBS Me...",
  "Auto-简报-Apple-Introduces-New-Mac-Studio-with-M5-Ma": "Apple Introduces New Mac Studio with M5 ...",
  "Auto-简报-App1｜ArkFlow：满足你的卡面收集癖，给信用卡做个卡面墙": "App1｜ArkFlow：满足你的卡面收集癖，给信用卡做个卡面墙",
  "Auto-简报-Anthropics-best-AI-model-struggles-to-attr": "Anthropics best AI model struggles to at...",
  "Auto-简报-Anthropic-最强模型难以吸引用户": "Anthropic 最强模型难以吸引用户",
  "Auto-简报-Anthropic-appears-to-be-AB-testing-reduced": "Anthropic appears to be AB testing reduc...",
  "Auto-简报-Another-Better-Lower-Bound-for-N17-Square": "Another Better Lower Bound for N17 Squar...",
  "Auto-简报-Announcing-Lennys-Jobs-The-best-place-in-t": "Announcing Lennys Jobs The best place in...",
  "Auto-简报-An-opinionated-guide-to-which-AI-to-use-to": "An opinionated guide to which AI to use ...",
  "Auto-简报-An-American-Engineer-in-China": "An American Engineer in China",
  "Auto-简报-Americas-Electricity-Gap": "Americas Electricity Gap",
  "Auto-简报-All-You-Need-To-Know-About-Warsh": "All You Need To Know About Warsh",
  "Auto-简报-Agentic-Context-Management-Memory-and-Cost": "Agentic Context Management Memory and Co...",
  "Auto-简报-AgentX-InferenceXv3-Does-CUDA-Moat-Hold-up": "AgentX - InferenceXv3 Does CUDA Moat Hol...",
  "Auto-简报-AWS-Acquires-DuckDB": "AWS Acquires DuckDB",
  "Auto-简报-AMDs-FP64-Boost-with-MI430X-Is-Even-Bigger": "AMDs FP64 Boost with MI430X Is Even Bigg...",
  "Auto-简报-AI的账单，不只由科技公司买单": "AI的账单，不只由科技公司买单",
  "Auto-简报-AI时代，我们可能都要走向灵活就业": "AI时代，我们可能都要走向灵活就业",
  "Auto-简报-AI代笔风潮之下的讨论和思考（上）": "AI代笔风潮之下的讨论和思考（上）",
  "Auto-简报-AI-时代的-Surface-Pro-7-改造指南：看板、轻量工作站与-Linux": "AI 时代的 Surface Pro 7 改造指南：看板、轻量工作站与 Linu...",
  "Auto-简报-AI-开始给自己造芯了，OpenAI-只用了九个月": "AI 开始给自己造芯了，OpenAI 只用了九个月",
  "Auto-简报-AI-原生企业：不是企业-AI": "AI 原生企业：不是企业  AI",
  "Auto-简报-AI-即将接管流量，而广告正在疯狂「末日反扑」": "AI 即将接管流量，而广告正在疯狂「末日反扑」",
  "Auto-简报-AI-助力改造非智能升降桌：智能升降、语音控制、多端联动……": "AI 助力改造非智能升降桌：智能升降、语音控制、多端联动……",
  "Auto-简报-AI-for-Science最难学会的，是换一个问题": "AI for Science最难学会的，是换一个问题",
  "Auto-简报-AI-Got-Good-at-Language-Now-Its-Learning-t": "AI Got Good at Language. Now Its Learnin...",
  "Auto-简报-A-shot-scraper-style-JSON-API-on-Bun-14s-n": "A shot-scraper-style JSON API on Bun 1.4...",
  "Auto-简报-A-preliminary-Qwen38-27B-model-card-is-liv": "A preliminary Qwen3.8-27B model card is ...",
  "Auto-简报-A-formal-degree-and-algorithmic-problem-so": "A formal degree and algorithmic problem-...",
  "Auto-简报-A-Minor-Detail": "A Minor Detail",
  "Auto-简报-A-Kantian-Critique-of-Sorry-by-Justin-Bieb": "A Kantian Critique of Sorry by Justin Bi...",
  "Auto-简报-A-Friendly-Introduction-to-Racket": "A Friendly Introduction to Racket",
  "Auto-简报-99元AI洗头、499元AI按摩…体验完深圳5款AI大保健，我碎了": "9.9元AI洗头、49.9元AI按摩…体验完深圳5款AI大保健，我碎了",
  "Auto-简报-7月宏观数据给了什么样的信号": "7月宏观数据给了什么样的信号",
  "Auto-简报-535B大模型直播训练三个月：代码、数据、Loss全公开，吴恩达公开力挺": "535B大模型直播训练三个月：代码、数据、Loss全公开，吴恩达公开力挺",
  "Auto-简报-4天消失2000亿，宇树为何遭遇抛售": "4天消失2000亿，宇树为何遭遇抛售",
  "Auto-简报-3万店之后，鸣鸣很忙还有什么弹药": "3万店之后，鸣鸣很忙还有什么弹药",
  "Auto-简报-38x-in-Ten-Months-Inside-One-of-Fintechs-F": "38x in Ten Months Inside One of Fintechs...",
  "Auto-简报-32-亿人口、9-万亿元市场，做餐饮也要开始抢老人了": "3.2 亿人口、9 万亿元市场，做餐饮也要开始抢老人了",
  "Auto-简报-29-Year-Olds-Can-Write-Memoirs-Too": "29-Year-Olds Can Write Memoirs Too",
  "Auto-简报-2798-万元起，泰钽-700-正式上市，越野-NOA-开上挂壁公路": "27.98 万元起，泰钽 700 正式上市，越野 NOA 开上挂壁公路",
  "Auto-简报-23-low-regret-recommendations-for-AI-polic": "23 low-regret recommendations for AI pol...",
  "Auto-简报-202634-App-Snore": "2026.34 App Snore",
  "Auto-简报-202633-The-CapEx-Train-Keeps-Rolling": "2026.33 The CapEx Train Keeps Rolling",
  "Auto-简报-130-亿美元，Hugging-Face-要卖了": "130 亿美元，Hugging Face 要卖了",
  "Auto-简报-12B-of-US-ratepayers-money-wasted-on-a-mod": "$12B of US ratepayers money wasted on a ..."
};
