export default {
  "Raw-逐字稿-【小Lin求职100问】Data-Analyst和Quant的区别在哪儿Data-A": "Raw_逐字稿_【小Lin求职100问】Data Analyst和Quant的区...",
  "Raw-翻译-attune-forms-is-now-on-PyPI-—-and-as-of-thi": "attune-forms is now on PyPI — and as of ...",
  "Raw-翻译-Python-Low-Level-Physical-Media-Storage-Arc": "[Python] Low-Level Physical Media  Stora...",
  "Raw-翻译-Yesterdays-eclipse-as-seen-from-Spain-simul": "Yesterdays eclipse as seen from Spain, s...",
  "Raw-翻译-Whats-everyone-working-on-this-week-332026": "Whats everyone working on this week 3320...",
  "Raw-翻译-Whats-Better-Than-Binary-–-Advent-of-Comput": "Whats Better Than Binary – Advent of Com...",
  "Raw-翻译-What-it-feels-like-to-work-with-Mythos": "What it feels like to work with Mythos",
  "Raw-翻译-What-is-the-status-of-web-development-in-ru": "What is the status of web development in...",
  "Raw-翻译-Weekly-Dose-of-Optimism-206": "Weekly Dose of Optimism 206",
  "Raw-翻译-Weekly-Dose-of-Optimism-205": "Weekly Dose of Optimism 205",
  "Raw-翻译-We-Tracked-a-Shipment-of-Rare-Books-It-Ende": "We Tracked a Shipment of Rare Books. It ...",
  "Raw-翻译-Trained-a-15B-to-write-shell-commands-so-Id": "Trained a 1.5B to write shell commands s...",
  "Raw-翻译-The-twilight-of-the-chatbots": "The twilight of the chatbots",
  "Raw-翻译-The-countdown-to-Qwen38-27B-starts-now": "The countdown to Qwen3.8-27B starts now!",
  "Raw-翻译-Teaching-Everyone-to-Fish-for-Tokens": "Teaching Everyone to Fish for Tokens",
  "Raw-翻译-TMLR-Relevance-and-Prestige-D": "TMLR Relevance and Prestige [D]",
  "Raw-翻译-Stop-Just-Stop": "Stop, Just Stop",
  "Raw-翻译-Slapping-Windows-11-PCs-with-a-Copilot-key": "Slapping Windows 11 PCs with a Copilot k...",
  "Raw-翻译-Saplings-Unstable-Ground": "Saplings Unstable Ground",
  "Raw-翻译-Samsung-Foundry-updates-process-roadmap-to": "Samsung Foundry updates process roadmap ...",
  "Raw-翻译-Rust-on-the-JVM-now-passes-99-of-official-u": "Rust on the JVM now passes 99 of officia...",
  "Raw-翻译-Ranked-The-Worlds-Busiest-Airlines-by-Fligh": "Ranked The Worlds Busiest Airlines by Fl...",
  "Raw-翻译-QwenQwen38-27B-·-released": "QwenQwen3.8-27B · released",
  "Raw-翻译-Qwen38-27B-is-identical-to-Qwen36-27B": "Qwen3.8-27B is identical to Qwen3.6-27B",
  "Raw-翻译-Qwen-38-27B-scores-52-on-the-Artificial-Ana": "Qwen 3.8 27B scores 52 on the Artificial...",
  "Raw-翻译-Qwen-38-27B-Released-Please-Share-Your-Expe": "Qwen 3.8 27B Released Please Share Your ...",
  "Raw-翻译-Other-Python-forums-Stack-Overflow": "Other Python forums - Stack Overflow",
  "Raw-翻译-MiniMax-Music3-released": "MiniMax-Music3 released!",
  "Raw-翻译-Markdown-SVG-upgrades": "Markdown SVG upgrades",
  "Raw-翻译-Made-a-cake-for-my-boyfriends-birthday": "Made a cake for my boyfriends birthday",
  "Raw-翻译-ITS-OUT": "ITS OUT",
  "Raw-翻译-I-wrote-an-AI-textbook-—-how-long-until-AI": "I wrote an AI textbook — how long until ...",
  "Raw-翻译-I-compiled-Dooms-renderer-into-a-21B-parame": "I compiled Dooms renderer into a 21B-par...",
  "Raw-翻译-How-is-the-qmusage-quota-for-Grok-46-in-cur": "How is the qmusage quota for Grok 4.6 in...",
  "Raw-翻译-Hey-Rustaceans-Got-a-question-Ask-here-3320": "Hey Rustaceans Got a question Ask here 3...",
  "Raw-翻译-Github-unslothai-unsloth": "Github__unslothai_unsloth",
  "Raw-翻译-Github-smicallef-spiderfoot": "Github__smicallef_spiderfoot",
  "Raw-翻译-Github-megadose-holehe": "Github__megadose_holehe",
  "Raw-翻译-Github-cursor-plugins": "Github__cursor_plugins",
  "Raw-翻译-Github-cordiverse-cordis": "Github__cordiverse_cordis",
  "Raw-翻译-GLM-53-How-Chinese-labs-keep-stride-with-th": "GLM-5.3 How Chinese labs keep stride wit...",
  "Raw-翻译-GLM-53-Released": "GLM 5.3 Released",
  "Raw-翻译-Friday-Daily-Thread-rPython-Meta-and-Free-T": "Friday Daily Thread rPython Meta and Fre...",
  "Raw-翻译-For-the-people-who-got-reviews-back-from-ne": "For the people who got reviews back from...",
  "Raw-翻译-Fixed-Jinja-chat-template-for-Qwen-35-36-an": "Fixed Jinja chat template for Qwen 3.5, ...",
  "Raw-翻译-EU-GPU-prices-are-up-19-in-one-month-tracke": "EU GPU prices are up ~19 in one month, t...",
  "Raw-翻译-City2Graph-A-Python-library-for-Heterogeneo": "City2Graph A Python library for Heteroge...",
  "Raw-翻译-Base-Power-Company-Chapter-3": "Base Power Company Chapter 3",
  "Raw-翻译-An-opinionated-guide-to-which-AI-to-use-to": "An opinionated guide to which AI to use ...",
  "Raw-翻译-AMDs-FP64-Boost-with-MI430X-Is-Even-Bigger": "AMDs FP64 Boost with MI430X Is Even Bigg...",
  "Raw-翻译-AI-Got-Good-at-Language-Now-Its-Learning-th": "AI Got Good at Language. Now Its Learnin...",
  "Raw-翻译-A-preliminary-Qwen38-27B-model-card-is-live": "A preliminary Qwen3.8-27B model card is ...",
  "Raw-翻译-38x-in-Ten-Months-Inside-One-of-Fintechs-Fa": "38x in Ten Months Inside One of Fintechs...",
  "Raw-翻译-23-low-regret-recommendations-for-AI-policy": "23 low-regret recommendations for AI pol...",
  "Raw-翻译-202633-The-CapEx-Train-Keeps-Rolling": "2026.33 The CapEx Train Keeps Rolling",
  "Auto-简报-【小Lin求职100问】Data-Analyst和Quant的区别在哪儿Data-A": "【小Lin求职100问】Data Analyst和Quant的区别在哪儿Data...",
  "Auto-简报-attune-forms-is-now-on-PyPI-—-and-as-of-th": "attune-forms is now on PyPI — and as of ...",
  "Auto-简报-Python-Low-Level-Physical-Media-Storage-Ar": "[Python] Low-Level Physical Media  Stora...",
  "Auto-简报-Yesterdays-eclipse-as-seen-from-Spain-simu": "Yesterdays eclipse as seen from Spain, s...",
  "Auto-简报-Whats-everyone-working-on-this-week-332026": "Whats everyone working on this week 3320...",
  "Auto-简报-Whats-Better-Than-Binary-–-Advent-of-Compu": "Whats Better Than Binary – Advent of Com...",
  "Auto-简报-What-it-feels-like-to-work-with-Mythos": "What it feels like to work with Mythos",
  "Auto-简报-What-is-the-status-of-web-development-in-r": "What is the status of web development in...",
  "Auto-简报-Weekly-Dose-of-Optimism-206": "Weekly Dose of Optimism 206",
  "Auto-简报-Weekly-Dose-of-Optimism-205": "Weekly Dose of Optimism 205",
  "Auto-简报-We-Tracked-a-Shipment-of-Rare-Books-It-End": "We Tracked a Shipment of Rare Books. It ...",
  "Auto-简报-Trained-a-15B-to-write-shell-commands-so-I": "Trained a 1.5B to write shell commands s...",
  "Auto-简报-The-twilight-of-the-chatbots": "The twilight of the chatbots",
  "Auto-简报-The-end-of-an-era-for-Chinas-economy": "The end of an era for Chinas economy",
  "Auto-简报-The-countdown-to-Qwen38-27B-starts-now": "The countdown to Qwen3.8-27B starts now!",
  "Auto-简报-Teaching-Everyone-to-Fish-for-Tokens": "Teaching Everyone to Fish for Tokens",
  "Auto-简报-TMLR-Relevance-and-Prestige-D": "TMLR Relevance and Prestige [D]",
  "Auto-简报-Stop-Just-Stop": "Stop, Just Stop",
  "Auto-简报-Slapping-Windows-11-PCs-with-a-Copilot-key": "Slapping Windows 11 PCs with a Copilot k...",
  "Auto-简报-Saplings-Unstable-Ground": "Saplings Unstable Ground",
  "Auto-简报-Samsung-Foundry-updates-process-roadmap-to": "Samsung Foundry updates process roadmap ...",
  "Auto-简报-Rust-on-the-JVM-now-passes-99-of-official": "Rust on the JVM now passes 99 of officia...",
  "Auto-简报-QwenQwen38-27B-·-released": "QwenQwen3.8-27B · released",
  "Auto-简报-Qwen38-27B-is-identical-to-Qwen36-27B": "Qwen3.8-27B is identical to Qwen3.6-27B",
  "Auto-简报-Qwen-38-27B-scores-52-on-the-Artificial-An": "Qwen 3.8 27B scores 52 on the Artificial...",
  "Auto-简报-Qwen-38-27B-Released-Please-Share-Your-Exp": "Qwen 3.8 27B Released Please Share Your ...",
  "Auto-简报-Other-Python-forums-Stack-Overflow": "Other Python forums - Stack Overflow",
  "Auto-简报-MiniMax-Music3-released": "MiniMax-Music3 released!",
  "Auto-简报-Markdown-SVG-upgrades": "Markdown SVG upgrades",
  "Auto-简报-Made-a-cake-for-my-boyfriends-birthday": "Made a cake for my boyfriends birthday",
  "Auto-简报-ITS-OUT": "ITS OUT",
  "Auto-简报-I-wrote-an-AI-textbook-—-how-long-until-AI": "I wrote an AI textbook — how long until ...",
  "Auto-简报-I-compiled-Dooms-renderer-into-a-21B-param": "I compiled Dooms renderer into a 21B-par...",
  "Auto-简报-How-is-the-qmusage-quota-for-Grok-46-in-cu": "How is the qmusage quota for Grok 4.6 in...",
  "Auto-简报-Hey-Rustaceans-Got-a-question-Ask-here-332": "Hey Rustaceans Got a question Ask here 3...",
  "Auto-简报-Github-unslothai-unsloth": "Github__unslothai_unsloth",
  "Auto-简报-Github-smicallef-spiderfoot": "Github__smicallef_spiderfoot",
  "Auto-简报-Github-megadose-holehe": "Github__megadose_holehe",
  "Auto-简报-Github-cursor-plugins": "Github__cursor_plugins",
  "Auto-简报-Github-cordiverse-cordis": "Github__cordiverse_cordis",
  "Auto-简报-GLM-53-How-Chinese-labs-keep-stride-with-t": "GLM-5.3 How Chinese labs keep stride wit...",
  "Auto-简报-GLM-53-Released": "GLM 5.3 Released",
  "Auto-简报-Friday-Daily-Thread-rPython-Meta-and-Free": "Friday Daily Thread rPython Meta and Fre...",
  "Auto-简报-For-the-people-who-got-reviews-back-from-n": "For the people who got reviews back from...",
  "Auto-简报-Fixed-Jinja-chat-template-for-Qwen-35-36-a": "Fixed Jinja chat template for Qwen 3.5, ...",
  "Auto-简报-EU-GPU-prices-are-up-19-in-one-month-track": "EU GPU prices are up ~19 in one month, t...",
  "Auto-简报-City2Graph-A-Python-library-for-Heterogene": "City2Graph A Python library for Heteroge...",
  "Auto-简报-Base-Power-Company-Chapter-3": "Base Power Company Chapter 3",
  "Auto-简报-An-opinionated-guide-to-which-AI-to-use-to": "An opinionated guide to which AI to use ...",
  "Auto-简报-AMDs-FP64-Boost-with-MI430X-Is-Even-Bigger": "AMDs FP64 Boost with MI430X Is Even Bigg...",
  "Auto-简报-AI-Got-Good-at-Language-Now-Its-Learning-t": "AI Got Good at Language. Now Its Learnin...",
  "Auto-简报-A-preliminary-Qwen38-27B-model-card-is-liv": "A preliminary Qwen3.8-27B model card is ...",
  "Auto-简报-38x-in-Ten-Months-Inside-One-of-Fintechs-F": "38x in Ten Months Inside One of Fintechs...",
  "Auto-简报-23-low-regret-recommendations-for-AI-polic": "23 low-regret recommendations for AI pol...",
  "Auto-简报-202633-The-CapEx-Train-Keeps-Rolling": "2026.33 The CapEx Train Keeps Rolling"
};
