export default {
  "Raw-逐字稿-【小Lin求职100问】Data-Analyst和Quant的区别在哪儿Data-A": "Raw_逐字稿_【小Lin求职100问】Data Analyst和Quant的区...",
  "Raw-逐字稿-Why-Wall-Street-is-Ignoring-Big-Techs-Debt": "Raw_逐字稿_Why Wall Street is Ignoring Big ...",
  "Raw-逐字稿-We-Need-To-Talk-About-Leopold": "Raw_逐字稿_We Need To Talk About Leopold",
  "Raw-逐字稿-This-new-startup-can-query-anywhere-youve": "Raw_逐字稿_This new startup can query anywh...",
  "Raw-逐字稿-The-summer-Math-fell-to-the-machines": "Raw_逐字稿_The summer Math fell to the mach...",
  "Raw-逐字稿-The-Insane-US-Japan-Currency-Bailout": "Raw_逐字稿_The Insane US-Japan Currency Bai...",
  "Raw-逐字稿-The-Biggest-Myths-in-Personal-Finance-Rati": "Raw_逐字稿_The Biggest Myths in Personal Fi...",
  "Raw-逐字稿-Stagflation-Explained": "Raw_逐字稿_Stagflation Explained",
  "Raw-逐字稿-Should-you-borrow-to-invest": "Raw_逐字稿_Should you borrow to invest",
  "Raw-逐字稿-Past-the-Point-of-No-Return": "Raw_逐字稿_Past the Point of No Return",
  "Raw-逐字稿-OpenAIs-AI-Agents-Just-Crossed-A-Line": "Raw_逐字稿_OpenAIs AI Agents Just Crossed A...",
  "Raw-逐字稿-How-Much-Would-an-AI-Crash-Destroy": "Raw_逐字稿_How Much Would an AI Crash Destr...",
  "Raw-逐字稿-Here-We-Go-Again": "Raw_逐字稿_Here We Go Again",
  "Raw-逐字稿-Finfluencer-Promotions-Are-Getting-Worse": "Raw_逐字稿_Finfluencer Promotions Are Getti...",
  "Raw-逐字稿-Different-Strengths-Different-Weaknesses": "Raw_逐字稿_Different Strengths  Different W...",
  "Raw-逐字稿-DeepSeek-is-back-and-Silicon-Valley-is-ter": "Raw_逐字稿_DeepSeek is back... and Silicon ...",
  "Raw-逐字稿-DeepSeek-Just-Made-Closed-AI-Look-Ridiculo": "Raw_逐字稿_DeepSeek Just Made Closed AI Loo...",
  "Raw-逐字稿-Claude-AI-Failed-650-Times…Then-Beat-The-H": "Raw_逐字稿_Claude AI Failed 650 Times…Then ...",
  "Raw-逐字稿-Canadas-Condo-Conundrum": "Raw_逐字稿_Canadas Condo Conundrum",
  "Raw-逐字稿-Bill-Bernstein-The-Money-Decisions-That-Ac": "Raw_逐字稿_Bill Bernstein The Money Decisio...",
  "Raw-翻译-🧠-Community-Wisdom-Favorite-Lennys-Product": "🧠 Community Wisdom Favorite Lennys Produ...",
  "Raw-翻译-🎙️-How-I-AI-How-a-solo-founder-used-Codex-a": "🎙️ How I AI How a solo founder used Code...",
  "Raw-翻译-迈威尔Marvell：贴钱结盟谷歌，能撬动博通墙角吗": "迈威尔Marvell：贴钱结盟谷歌，能撬动博通墙角吗",
  "Raw-翻译-越会用-AI-的人，学习能力退化得越快": "越会用 AI 的人，学习能力退化得越快",
  "Raw-翻译-让-PC-与-HomePod-互联：音频串流工具-WinAirCast": "让 PC 与 HomePod 互联：音频串流工具 WinAirCast",
  "Raw-翻译-美加貿易協議談崩-卡尼面臨關鍵考驗": "美加貿易協議談崩 卡尼面臨關鍵考驗",
  "Raw-翻译-线下活动｜Echoes-Remain：迈克尔杰克逊-68-周年诞辰唱片展": "线下活动｜Echoes Remain：迈克尔杰克逊 68 周年诞辰唱片展",
  "Raw-翻译-早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价158万元LV否认「起诉国家知": "早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价1.58万元LV否认「起...",
  "Raw-翻译-日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗": "日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗",
  "Raw-翻译-微信灰测「按住转文字」功能被吐槽；DeepSeek-上线多模态功能；应急机械拉手难操作": "微信灰测「按住转文字」功能被吐槽；DeepSeek 上线多模态功能；应急机械拉手...",
  "Raw-翻译-张丹丹在学术上是扶不起的，不要再强行挽尊了": "张丹丹在学术上是扶不起的，不要再强行挽尊了",
  "Raw-翻译-年轻人的网络社交，正在偷偷鸽化": "年轻人的网络社交，正在偷偷鸽化",
  "Raw-翻译-因门把手安全隐患特斯拉在华召回近-300-万辆车": "因门把手安全隐患特斯拉在华召回近 300 万辆车",
  "Raw-翻译-台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何": "台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何",
  "Raw-翻译-中國機器人打破人類百米短跑世界紀錄": "中國機器人打破人類百米短跑世界紀錄",
  "Raw-翻译-又贵又难吃的歹毒漂亮饭，年轻人为什么抢着买单": "又贵又难吃的歹毒漂亮饭，年轻人为什么抢着买单",
  "Raw-翻译-smolmachines-smolvm-as-a-sandbox-for-untrus": "smolmachines  smolvm as a sandbox for un...",
  "Raw-翻译-llm-openrouter-07": "llm-openrouter 0.7",
  "Raw-翻译-llm-033": "llm 0.33",
  "Raw-翻译-llm-0321": "llm 0.32.1",
  "Raw-翻译-hdiutil-is-deprecated-in-macOS-27-Golden-Ga": "hdiutil is deprecated in macOS 27 Golden...",
  "Raw-翻译-attune-forms-is-now-on-PyPI-—-and-as-of-thi": "attune-forms is now on PyPI — and as of ...",
  "Raw-翻译-Python-Low-Level-Physical-Media-Storage-Arc": "[Python] Low-Level Physical Media  Stora...",
  "Raw-翻译-AINews-Poolside-gets-12B-reverse-execuhire": "[AINews] Poolside gets $12B reverse-exec...",
  "Raw-翻译-AINews-Memory-prices-up-500-in-12-months": "[AINews] Memory prices up 500 in 12 mont...",
  "Raw-翻译-AINews-Death-of-Params-Zai-CEO-Jie-Tang-on": "[AINews] Death of Params Z.ai CEO Jie Ta...",
  "Raw-翻译-AINews-10-worse-100x-cheaper-10000x-faster": "[AINews] 10 worse, 100x cheaper, 10000x ...",
  "Raw-翻译-Young-Money-Launch-Week-Update": "Young Money Launch Week Update",
  "Raw-翻译-Yesterdays-eclipse-as-seen-from-Spain-simul": "Yesterdays eclipse as seen from Spain, s...",
  "Raw-翻译-Windows-是-AI-PC-路上的绊脚石": "Windows 是 AI PC 路上的绊脚石",
  "Raw-翻译-Wi-Fi-8-is-the-first-wireless-upgrade-in-ye": "Wi-Fi 8 is the first wireless upgrade in...",
  "Raw-翻译-Why-were-investing-in-Tomo": "Why were investing in Tomo",
  "Raw-翻译-Why-Chinas-AI-Bubble-Is-Also-Industrial-Pol": "Why Chinas AI Bubble Is Also Industrial ...",
  "Raw-翻译-Where-to-eat-in-San-Francisco": "Where to eat in San Francisco",
  "Raw-翻译-Whats-everyone-working-on-this-week-332026": "Whats everyone working on this week 3320...",
  "Raw-翻译-Whats-Better-Than-Binary-–-Advent-of-Comput": "Whats Better Than Binary – Advent of Com...",
  "Raw-翻译-What-it-feels-like-to-work-with-Mythos": "What it feels like to work with Mythos",
  "Raw-翻译-What-is-the-status-of-web-development-in-ru": "What is the status of web development in...",
  "Raw-翻译-What-We-Lost-When-Search-Stopped-Making-Us": "What We Lost When Search Stopped Making ...",
  "Raw-翻译-Weekly-Dose-of-Optimism-207": "Weekly Dose of Optimism 207",
  "Raw-翻译-Weekly-Dose-of-Optimism-206": "Weekly Dose of Optimism 206",
  "Raw-翻译-Weekly-Dose-of-Optimism-205": "Weekly Dose of Optimism 205",
  "Raw-翻译-We-Tracked-a-Shipment-of-Rare-Books-It-Ende": "We Tracked a Shipment of Rare Books. It ...",
  "Raw-翻译-Using-Local-Coding-Agents": "Using Local Coding Agents",
  "Raw-翻译-Ultra-High-Interactivity-on-NVIDIA-GPUs-Til": "Ultra-High Interactivity on NVIDIA GPUs ...",
  "Raw-翻译-Trained-a-15B-to-write-shell-commands-so-Id": "Trained a 1.5B to write shell commands s...",
  "Raw-翻译-Tragically-as-many-as-9625-out-of-every-10k": "Tragically, as many as 9625 out of every...",
  "Raw-翻译-Tims中国：成不了星巴克，也学不会瑞幸": "Tims中国：成不了星巴克，也学不会瑞幸",
  "Raw-翻译-This-is-a-great-sub-regardless-of-what-comp": "This is a great sub, regardless of what ...",
  "Raw-翻译-The-wayfinder-Skill-Navigating-the-Fog-of-W": "The wayfinder Skill Navigating the Fog o...",
  "Raw-翻译-The-twilight-of-the-chatbots": "The twilight of the chatbots",
  "Raw-翻译-The-end-of-an-era-for-Chinas-economy": "The end of an era for Chinas economy",
  "Raw-翻译-The-countdown-to-Qwen38-27B-starts-now": "The countdown to Qwen3.8-27B starts now!",
  "Raw-翻译-The-Supreme-Court-Ruled-Against-Trumps-Tari": "The Supreme Court Ruled Against Trumps T...",
  "Raw-翻译-The-Sloppification-of-Peptides": "The Sloppification of Peptides",
  "Raw-翻译-The-Rise-of-Chinas-Electric-Vehicle-Industr": "The Rise of Chinas Electric Vehicle Indu...",
  "Raw-翻译-The-Religious-Experience-of-Philip-K-Dick-b": "The Religious Experience of Philip K. Di...",
  "Raw-翻译-The-Pulse-Quitting-Spotify-Podcasts-over-re": "The Pulse Quitting Spotify Podcasts over...",
  "Raw-翻译-The-Pulse-Metas-self-inflicted-resignation": "The Pulse Metas self-inflicted resignati...",
  "Raw-翻译-The-Pulse-Groks-CLI-caught-uploading-all-yo": "The Pulse Groks CLI caught uploading all...",
  "Raw-翻译-The-Pulse-Bending-Spoons-Acquisition-Strate": "The Pulse Bending Spoons Acquisition Str...",
  "Raw-翻译-The-Maradona-Theory-of-Interest-Rates": "The Maradona Theory of Interest Rates",
  "Raw-翻译-The-Golden-Rule-for-Becoming-a-Better-Write": "The Golden Rule for Becoming a Better Wr...",
  "Raw-翻译-The-Evolution-of-the-Agent-Harness": "The Evolution of the Agent Harness",
  "Raw-翻译-The-End-of-an-Athlon": "The End of an Athlon",
  "Raw-翻译-The-Best-Charity-of-the-Next-50-Years-Might": "The Best Charity of the Next 50 Years Mi...",
  "Raw-翻译-The-Art-of-Self-Promotion": "The Art of Self-Promotion",
  "Raw-翻译-The-Art-and-Beauty-of-Blade-Runner": "The Art and Beauty of Blade Runner",
  "Raw-翻译-Teaching-Everyone-to-Fish-for-Tokens": "Teaching Everyone to Fish for Tokens",
  "Raw-翻译-Taiwans-Modern-Miracle": "Taiwans Modern Miracle",
  "Raw-翻译-TMLR-Relevance-and-Prestige-D": "TMLR Relevance and Prestige [D]",
  "Raw-翻译-Sydney-Marathon-medal-mistakenly-depicts-Mu": "Sydney Marathon medal mistakenly depicts...",
  "Raw-翻译-Stop-Just-Stop": "Stop, Just Stop",
  "Raw-翻译-Stop-Making-TUIs": "Stop Making TUIs",
  "Raw-翻译-Software-Engineering-in-the-Agentic-Era": "Software Engineering in the Agentic Era",
  "Raw-翻译-Slapping-Windows-11-PCs-with-a-Copilot-key": "Slapping Windows 11 PCs with a Copilot k...",
  "Raw-翻译-Simulation-the-new-Scaling-Law-—-Joon-Sung": "Simulation the new Scaling Law — Joon Su...",
  "Raw-翻译-Show-HN-Make-your-logo-extra-bright-on-HDR": "Show HN Make your logo extra bright on H...",
  "Raw-翻译-Show-HN-AgentSight-–-eBPF-observability-for": "Show HN AgentSight – eBPF observability ...",
  "Raw-翻译-Scientists-release-biggest-2D-map-of-the-un": "Scientists release biggest 2D map of the...",
  "Raw-翻译-Saplings-Unstable-Ground": "Saplings Unstable Ground",
  "Raw-翻译-Samsung-Foundry-updates-process-roadmap-to": "Samsung Foundry updates process roadmap ...",
  "Raw-翻译-SalesPatriot-YC-W25-Is-Hiring-Forward-Deplo": "SalesPatriot YC W25 Is Hiring Forward De...",
  "Raw-翻译-Rust-on-the-JVM-now-passes-99-of-official-u": "Rust on the JVM now passes 99 of officia...",
  "Raw-翻译-Run-It-Hot-Yet-Again": "Run It Hot, Yet Again",
  "Raw-翻译-Rockstar-向微软和-Discord-发去法庭传票以识别-GTA6-泄密者身份": "Rockstar 向微软和 Discord 发去法庭传票以识别 GTA6 泄密者...",
  "Raw-翻译-Roblox-RBLX-Schlep-and-the-Streisand-Effect": "Roblox RBLX Schlep and the Streisand Eff...",
  "Raw-翻译-Rebuilding-our-Electron-meeting-recording-e": "Rebuilding our Electron meeting-recordin...",
  "Raw-翻译-Ranked-The-Worlds-Largest-Gold-Producers-20": "Ranked The Worlds Largest Gold Producers...",
  "Raw-翻译-Ranked-The-Worlds-Largest-Cities-1950-2100": "Ranked The Worlds Largest Cities 1950-21...",
  "Raw-翻译-Ranked-The-Worlds-Busiest-Airlines-by-Fligh": "Ranked The Worlds Busiest Airlines by Fl...",
  "Raw-翻译-Ranked-The-Most-Popular-AI-Tools-in-2026": "Ranked The Most Popular AI Tools in 2026",
  "Raw-翻译-Ranked-The-Highest-Mountain-on-Every-Contin": "Ranked The Highest Mountain on Every Con...",
  "Raw-翻译-Ranked-The-Biggest-Risks-to-the-US-Economy": "Ranked The Biggest Risks to the U.S. Eco...",
  "Raw-翻译-Ranked-The-20-Highest-Grossing-Concert-Tour": "Ranked The 20 Highest-Grossing Concert T...",
  "Raw-翻译-Ranked-Military-Spending-in-OECD-Countries": "Ranked Military Spending in OECD Countri...",
  "Raw-翻译-Ranked-Countries-With-the-Highest-Senior-Po": "Ranked Countries With the Highest Senior...",
  "Raw-翻译-Ranked-Car-Brands-With-the-Most-Loyal-Custo": "Ranked Car Brands With the Most Loyal Cu...",
  "Raw-翻译-QwenQwen38-27B-·-released": "QwenQwen3.8-27B · released",
  "Raw-翻译-Qwen38-27B-is-identical-to-Qwen36-27B": "Qwen3.8-27B is identical to Qwen3.6-27B",
  "Raw-翻译-Qwen38-27B-Q6-is-a-beast-at-agentic-coding": "Qwen3.8-27B Q6 is a beast at agentic cod...",
  "Raw-翻译-Qwen-38-27B-scores-52-on-the-Artificial-Ana": "Qwen 3.8 27B scores 52 on the Artificial...",
  "Raw-翻译-Qwen-38-27B-Released-Please-Share-Your-Expe": "Qwen 3.8 27B Released Please Share Your ...",
  "Raw-翻译-Quoting-Matt-Webb": "Quoting Matt Webb",
  "Raw-翻译-Quoting-Linus-Torvalds": "Quoting Linus Torvalds",
  "Raw-翻译-PayPal-Declined": "PayPal, Declined",
  "Raw-翻译-Overcaffeinated-in-Indonesia": "Overcaffeinated in Indonesia",
  "Raw-翻译-Over-Target": "Over Target",
  "Raw-翻译-Other-Python-forums-Stack-Overflow": "Other Python forums - Stack Overflow",
  "Raw-翻译-North-Korean-Messiah": "North Korean Messiah",
  "Raw-翻译-NetBSD-and-My-Life-2005": "NetBSD and My Life 2005",
  "Raw-翻译-NanoGPT-Speedrun-Frontier": "NanoGPT Speedrun Frontier",
  "Raw-翻译-More-than-just-code-review": "More than just code review",
  "Raw-翻译-MiniMax-Music3-released": "MiniMax-Music3 released!",
  "Raw-翻译-Markdown-SVG-upgrades": "Markdown SVG upgrades",
  "Raw-翻译-Marginal-Rations": "Marginal Rations",
  "Raw-翻译-Mapped-Where-Young-Americans-Are-Buying-Hom": "Mapped Where Young Americans Are Buying ...",
  "Raw-翻译-Mapped-Where-Homelessness-Rates-Are-Highest": "Mapped Where Homelessness Rates Are High...",
  "Raw-翻译-Made-a-cake-for-my-boyfriends-birthday": "Made a cake for my boyfriends birthday",
  "Raw-翻译-LiteLLM-YC-W23-Is-Hiring-–-Rust-Performance": "LiteLLM YC W23 Is Hiring – Rust  Perform...",
  "Raw-翻译-Leopolds-Fall": "Leopolds Fall",
  "Raw-翻译-Learning-about-The-Unix-Time-Sharing-System": "Learning about The Unix Time-Sharing Sys...",
  "Raw-翻译-Knowing-When-to-Stop-The-Art-of-Making-a-Lo": "Knowing When to Stop The Art of Making a...",
  "Raw-翻译-Japan-tried-to-build-an-operating-system-fo": "Japan tried to build an operating system...",
  "Raw-翻译-JIT-Compiling-Code-in-5μs": "JIT Compiling Code in 5μs",
  "Raw-翻译-Initial-focus-for-our-partnership-with-Moto": "Initial focus for our partnership with M...",
  "Raw-翻译-Import-AI-469-Science-AI;-RSI-simulator;-an": "Import AI 469 Science AI; RSI simulator;...",
  "Raw-翻译-Import-AI-468-23-RSI-ideas;-PostTrainBench;": "Import AI 468 23 RSI ideas; PostTrainBen...",
  "Raw-翻译-Import-AI-467-Self-sustaining-AI-viruses;-p": "Import AI 467 Self-sustaining AI viruses...",
  "Raw-翻译-ITS-OUT": "ITS OUT",
  "Raw-翻译-I-wrote-an-AI-textbook-—-how-long-until-AI": "I wrote an AI textbook — how long until ...",
  "Raw-翻译-I-tested-Grok-Bot-Grok-46-and-Cursor-Origin": "I tested Grok Bot, Grok 4.6, and Cursor ...",
  "Raw-翻译-I-gave-Qwen-38-27B-a-reverse-engineering-jo": "I gave Qwen 3.8 27B a reverse-engineerin...",
  "Raw-翻译-I-compiled-Dooms-renderer-into-a-21B-parame": "I compiled Dooms renderer into a 21B-par...",
  "Raw-翻译-How-is-the-qmusage-quota-for-Grok-46-in-cur": "How is the qmusage quota for Grok 4.6 in...",
  "Raw-翻译-How-Claude-Watermarks-AI-Generated-Text": "How Claude Watermarks AI-Generated Text",
  "Raw-翻译-Hook-hold-harvest-and-hide-Metas-alleged-st": "Hook, hold, harvest and hide Metas alleg...",
  "Raw-翻译-Hey-Rustaceans-Got-a-question-Ask-here-3320": "Hey Rustaceans Got a question Ask here 3...",
  "Raw-翻译-Here-Comes-the-Repo-Man": "Here Comes the Repo Man",
  "Raw-翻译-Great-Scott": "Great Scott",
  "Raw-翻译-Github-unslothai-unsloth": "Github__unslothai_unsloth",
  "Raw-翻译-Github-smicallef-spiderfoot": "Github__smicallef_spiderfoot",
  "Raw-翻译-Github-openai-codex": "Github__openai_codex",
  "Raw-翻译-Github-obra-superpowers": "Github__obra_superpowers",
  "Raw-翻译-Github-modular-modular": "Github__modular_modular",
  "Raw-翻译-Github-megadose-holehe": "Github__megadose_holehe",
  "Raw-翻译-Github-mattpocock-skills": "Github__mattpocock_skills",
  "Raw-翻译-Github-cursor-plugins": "Github__cursor_plugins",
  "Raw-翻译-Github-cordiverse-cordis": "Github__cordiverse_cordis",
  "Raw-翻译-Github-affaan-m-ECC": "Github__affaan-m_ECC",
  "Raw-翻译-Github-Wei-Shaw-sub2api": "Github__Wei-Shaw_sub2api",
  "Raw-翻译-GLM-53-How-Chinese-labs-keep-stride-with-th": "GLM-5.3 How Chinese labs keep stride wit...",
  "Raw-翻译-GLM-53-Released": "GLM 5.3 Released",
  "Raw-翻译-Friday-Daily-Thread-rPython-Meta-and-Free-T": "Friday Daily Thread rPython Meta and Fre...",
  "Raw-翻译-For-the-people-who-got-reviews-back-from-ne": "For the people who got reviews back from...",
  "Raw-翻译-Fixed-Jinja-chat-template-for-Qwen-35-36-an": "Fixed Jinja chat template for Qwen 3.5, ...",
  "Raw-翻译-Financing-the-AI-Boom-3": "Financing the AI Boom 3",
  "Raw-翻译-Fast-and-Hard-Code": "Fast and Hard Code",
  "Raw-翻译-Endangered-Specious": "Endangered Specious",
  "Raw-翻译-Economists-should-be-worried-about-birth-ra": "Economists should be worried about birth...",
  "Raw-翻译-Early-Humans-Likely-Ate-Carbs-and-Sugary-Fo": "Early Humans Likely Ate Carbs and Sugary...",
  "Raw-翻译-EU-GPU-prices-are-up-19-in-one-month-tracke": "EU GPU prices are up ~19 in one month, t...",
  "Raw-翻译-Dirty-Secrets-Eight-SMIDs": "Dirty Secrets Eight SMIDs",
  "Raw-翻译-Digging-the-grave-of-my-skills-Hollywood-cr": "Digging the grave of my skills Hollywood...",
  "Raw-翻译-DeepSeek-周末用量统一低价收费；特斯拉-9-月-3-日首秀-Cybercab；": "DeepSeek 周末用量统一低价收费；特斯拉 9 月 3 日首秀 Cyberc...",
  "Raw-翻译-Controlling-Reasoning-Effort-in-LLMs": "Controlling Reasoning Effort in LLMs",
  "Raw-翻译-Collaborative-Fund-Conversations-Jacob-Hode": "Collaborative Fund Conversations Jacob H...",
  "Raw-翻译-Claudette-Make-Claude-Stop-Talking-Like-a-B": "Claudette Make Claude Stop Talking Like ...",
  "Raw-翻译-City2Graph-A-Python-library-for-Heterogeneo": "City2Graph A Python library for Heteroge...",
  "Raw-翻译-ChatGPT-search-now-uses-the-siteoperator-at": "ChatGPT search now uses the siteoperator...",
  "Raw-翻译-Cerebrass-Next-Generation-CS-4-Fast-Just-Go": "Cerebrass Next Generation CS-4 Fast Just...",
  "Raw-翻译-Cancer-Related-Mortality-Among-US-Pilots-an": "Cancer-Related Mortality Among US Pilots...",
  "Raw-翻译-Canada-suspends-trade-negotiations-with-USA": "Canada suspends trade negotiations with ...",
  "Raw-翻译-Building-an-AI-Text-Detector-From-Scratch": "Building an AI Text Detector From Scratc...",
  "Raw-翻译-Bringing-the-cybersecurity-capabilities-of": "Bringing the cybersecurity capabilities ...",
  "Raw-翻译-Belgian-car-salesman-becomes-prince-after-D": "Belgian car salesman becomes prince afte...",
  "Raw-翻译-Base-Power-Company-Chapter-3": "Base Power Company Chapter 3",
  "Raw-翻译-Are-we-watching-the-US-go-bankrupt": "Are we watching the U.S. go bankrupt",
  "Raw-翻译-Are-Open-Models-Catching-Up": "Are Open Models Catching Up",
  "Raw-翻译-Anthropic-appears-to-be-AB-testing-reduced": "Anthropic appears to be AB testing reduc...",
  "Raw-翻译-Another-Better-Lower-Bound-for-N17-Square-P": "Another Better Lower Bound for N17 Squar...",
  "Raw-翻译-Announcing-Lennys-Jobs-The-best-place-in-th": "Announcing Lennys Jobs The best place in...",
  "Raw-翻译-An-opinionated-guide-to-which-AI-to-use-to": "An opinionated guide to which AI to use ...",
  "Raw-翻译-Americas-Electricity-Gap": "Americas Electricity Gap",
  "Raw-翻译-All-You-Need-To-Know-About-Warsh": "All You Need To Know About Warsh",
  "Raw-翻译-AMDs-FP64-Boost-with-MI430X-Is-Even-Bigger": "AMDs FP64 Boost with MI430X Is Even Bigg...",
  "Raw-翻译-AI-时代的-Surface-Pro-7-改造指南：看板、轻量工作站与-Linux-笔": "AI 时代的 Surface Pro 7 改造指南：看板、轻量工作站与 Linu...",
  "Raw-翻译-AI-即将接管流量，而广告正在疯狂「末日反扑」": "AI 即将接管流量，而广告正在疯狂「末日反扑」",
  "Raw-翻译-AI-Got-Good-at-Language-Now-Its-Learning-th": "AI Got Good at Language. Now Its Learnin...",
  "Raw-翻译-A-shot-scraper-style-JSON-API-on-Bun-14s-ne": "A shot-scraper-style JSON API on Bun 1.4...",
  "Raw-翻译-A-preliminary-Qwen38-27B-model-card-is-live": "A preliminary Qwen3.8-27B model card is ...",
  "Raw-翻译-A-formal-degree-and-algorithmic-problem-sol": "A formal degree and algorithmic problem-...",
  "Raw-翻译-A-Minor-Detail": "A Minor Detail",
  "Raw-翻译-A-Kantian-Critique-of-Sorry-by-Justin-Biebe": "A Kantian Critique of Sorry by Justin Bi...",
  "Raw-翻译-A-Friendly-Introduction-to-Racket": "A Friendly Introduction to Racket",
  "Raw-翻译-38x-in-Ten-Months-Inside-One-of-Fintechs-Fa": "38x in Ten Months Inside One of Fintechs...",
  "Raw-翻译-3-分钟冲刺跑产生的分子反应与-90-分钟中等强度运动截然不同": "3 分钟冲刺跑产生的分子反应与 90 分钟中等强度运动截然不同",
  "Raw-翻译-29-Year-Olds-Can-Write-Memoirs-Too": "29-Year-Olds Can Write Memoirs Too",
  "Raw-翻译-23-low-regret-recommendations-for-AI-policy": "23 low-regret recommendations for AI pol...",
  "Raw-翻译-202634-App-Snore": "2026.34 App Snore",
  "Raw-翻译-202633-The-CapEx-Train-Keeps-Rolling": "2026.33 The CapEx Train Keeps Rolling",
  "Raw-翻译-12B-of-US-ratepayers-money-wasted-on-a-mode": "$12B of US ratepayers money wasted on a ...",
  "Raw-微信-猫笔刀-算一笔烂账": "Raw_微信_猫笔刀_算一笔烂账",
  "Auto-简报-🧠-Community-Wisdom-Favorite-Lennys-Product": "🧠 Community Wisdom Favorite Lennys Produ...",
  "Auto-简报-🎙️-How-I-AI-How-a-solo-founder-used-Codex": "🎙️ How I AI How a solo founder used Code...",
  "Auto-简报-越会用-AI-的人，学习能力退化得越快": "越会用 AI 的人，学习能力退化得越快",
  "Auto-简报-美加貿易協議談崩-卡尼面臨關鍵考驗": "美加貿易協議談崩 卡尼面臨關鍵考驗",
  "Auto-简报-早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价158万元LV否认「起诉国家": "早报｜摄像头AirPods或配备拍摄指示灯问界儿童车售价1.58万元LV否认「起...",
  "Auto-简报-日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗": "日租60元，被索赔10万，全季起诉小旅馆，老板苦言：大公司就不能先发个律师函吗",
  "Auto-简报-微信灰测「按住转文字」功能被吐槽；DeepSeek-上线多模态功能；应急机械拉手难操": "微信灰测「按住转文字」功能被吐槽；DeepSeek 上线多模态功能；应急机械拉手...",
  "Auto-简报-微信-猫笔刀-算一笔烂账": "微信_猫笔刀_算一笔烂账",
  "Auto-简报-张丹丹在学术上是扶不起的，不要再强行挽尊了": "张丹丹在学术上是扶不起的，不要再强行挽尊了",
  "Auto-简报-年轻人的网络社交，正在偷偷鸽化": "年轻人的网络社交，正在偷偷鸽化",
  "Auto-简报-台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何": "台灣「三大公投」：時隔一年再公投，這次投什麼通過門檻為何",
  "Auto-简报-中國機器人打破人類百米短跑世界紀錄": "中國機器人打破人類百米短跑世界紀錄",
  "Auto-简报-【小Lin求职100问】Data-Analyst和Quant的区别在哪儿Data-A": "【小Lin求职100问】Data Analyst和Quant的区别在哪儿Data...",
  "Auto-简报-smolmachines-smolvm-as-a-sandbox-for-untru": "smolmachines  smolvm as a sandbox for un...",
  "Auto-简报-llm-openrouter-07": "llm-openrouter 0.7",
  "Auto-简报-llm-033": "llm 0.33",
  "Auto-简报-llm-0321": "llm 0.32.1",
  "Auto-简报-hdiutil-is-deprecated-in-macOS-27-Golden-G": "hdiutil is deprecated in macOS 27 Golden...",
  "Auto-简报-attune-forms-is-now-on-PyPI-—-and-as-of-th": "attune-forms is now on PyPI — and as of ...",
  "Auto-简报-Python-Low-Level-Physical-Media-Storage-Ar": "[Python] Low-Level Physical Media  Stora...",
  "Auto-简报-AINews-Poolside-gets-12B-reverse-execuhire": "[AINews] Poolside gets $12B reverse-exec...",
  "Auto-简报-AINews-Memory-prices-up-500-in-12-months": "[AINews] Memory prices up 500 in 12 mont...",
  "Auto-简报-AINews-Death-of-Params-Zai-CEO-Jie-Tang-on": "[AINews] Death of Params Z.ai CEO Jie Ta...",
  "Auto-简报-AINews-10-worse-100x-cheaper-10000x-faster": "[AINews] 10 worse, 100x cheaper, 10000x ...",
  "Auto-简报-Young-Money-Launch-Week-Update": "Young Money Launch Week Update",
  "Auto-简报-Yesterdays-eclipse-as-seen-from-Spain-simu": "Yesterdays eclipse as seen from Spain, s...",
  "Auto-简报-Windows-是-AI-PC-路上的绊脚石": "Windows 是 AI PC 路上的绊脚石",
  "Auto-简报-Wi-Fi-8-is-the-first-wireless-upgrade-in-y": "Wi-Fi 8 is the first wireless upgrade in...",
  "Auto-简报-Why-were-investing-in-Tomo": "Why were investing in Tomo",
  "Auto-简报-Why-Wall-Street-is-Ignoring-Big-Techs-Debt": "Why Wall Street is Ignoring Big Techs De...",
  "Auto-简报-Why-Chinas-AI-Bubble-Is-Also-Industrial-Po": "Why Chinas AI Bubble Is Also Industrial ...",
  "Auto-简报-Where-to-eat-in-San-Francisco": "Where to eat in San Francisco",
  "Auto-简报-Whats-everyone-working-on-this-week-332026": "Whats everyone working on this week 3320...",
  "Auto-简报-Whats-Better-Than-Binary-–-Advent-of-Compu": "Whats Better Than Binary – Advent of Com...",
  "Auto-简报-What-it-feels-like-to-work-with-Mythos": "What it feels like to work with Mythos",
  "Auto-简报-What-is-the-status-of-web-development-in-r": "What is the status of web development in...",
  "Auto-简报-What-We-Lost-When-Search-Stopped-Making-Us": "What We Lost When Search Stopped Making ...",
  "Auto-简报-Weekly-Dose-of-Optimism-207": "Weekly Dose of Optimism 207",
  "Auto-简报-Weekly-Dose-of-Optimism-206": "Weekly Dose of Optimism 206",
  "Auto-简报-Weekly-Dose-of-Optimism-205": "Weekly Dose of Optimism 205",
  "Auto-简报-We-Tracked-a-Shipment-of-Rare-Books-It-End": "We Tracked a Shipment of Rare Books. It ...",
  "Auto-简报-We-Need-To-Talk-About-Leopold": "We Need To Talk About Leopold",
  "Auto-简报-Using-Local-Coding-Agents": "Using Local Coding Agents",
  "Auto-简报-Ultra-High-Interactivity-on-NVIDIA-GPUs-Ti": "Ultra-High Interactivity on NVIDIA GPUs ...",
  "Auto-简报-Trained-a-15B-to-write-shell-commands-so-I": "Trained a 1.5B to write shell commands s...",
  "Auto-简报-Tragically-as-many-as-9625-out-of-every-10": "Tragically, as many as 9625 out of every...",
  "Auto-简报-This-new-startup-can-query-anywhere-youve": "This new startup can query anywhere youv...",
  "Auto-简报-This-is-a-great-sub-regardless-of-what-com": "This is a great sub, regardless of what ...",
  "Auto-简报-The-wayfinder-Skill-Navigating-the-Fog-of": "The wayfinder Skill Navigating the Fog o...",
  "Auto-简报-The-twilight-of-the-chatbots": "The twilight of the chatbots",
  "Auto-简报-The-summer-Math-fell-to-the-machines": "The summer Math fell to the machines",
  "Auto-简报-The-end-of-an-era-for-Chinas-economy": "The end of an era for Chinas economy",
  "Auto-简报-The-countdown-to-Qwen38-27B-starts-now": "The countdown to Qwen3.8-27B starts now!",
  "Auto-简报-The-Supreme-Court-Ruled-Against-Trumps-Tar": "The Supreme Court Ruled Against Trumps T...",
  "Auto-简报-The-Sloppification-of-Peptides": "The Sloppification of Peptides",
  "Auto-简报-The-Rise-of-Chinas-Electric-Vehicle-Indust": "The Rise of Chinas Electric Vehicle Indu...",
  "Auto-简报-The-Religious-Experience-of-Philip-K-Dick": "The Religious Experience of Philip K. Di...",
  "Auto-简报-The-Pulse-Quitting-Spotify-Podcasts-over-r": "The Pulse Quitting Spotify Podcasts over...",
  "Auto-简报-The-Pulse-Metas-self-inflicted-resignation": "The Pulse Metas self-inflicted resignati...",
  "Auto-简报-The-Pulse-Groks-CLI-caught-uploading-all-y": "The Pulse Groks CLI caught uploading all...",
  "Auto-简报-The-Pulse-Bending-Spoons-Acquisition-Strat": "The Pulse Bending Spoons Acquisition Str...",
  "Auto-简报-The-Maradona-Theory-of-Interest-Rates": "The Maradona Theory of Interest Rates",
  "Auto-简报-The-Insane-US-Japan-Currency-Bailout": "The Insane US-Japan Currency Bailout",
  "Auto-简报-The-Golden-Rule-for-Becoming-a-Better-Writ": "The Golden Rule for Becoming a Better Wr...",
  "Auto-简报-The-Evolution-of-the-Agent-Harness": "The Evolution of the Agent Harness",
  "Auto-简报-The-End-of-an-Athlon": "The End of an Athlon",
  "Auto-简报-The-Biggest-Myths-in-Personal-Finance-Rati": "The Biggest Myths in Personal Finance  R...",
  "Auto-简报-The-Best-Charity-of-the-Next-50-Years-Migh": "The Best Charity of the Next 50 Years Mi...",
  "Auto-简报-The-Art-of-Self-Promotion": "The Art of Self-Promotion",
  "Auto-简报-The-Art-and-Beauty-of-Blade-Runner": "The Art and Beauty of Blade Runner",
  "Auto-简报-Teaching-Everyone-to-Fish-for-Tokens": "Teaching Everyone to Fish for Tokens",
  "Auto-简报-Taiwans-Modern-Miracle": "Taiwans Modern Miracle",
  "Auto-简报-TMLR-Relevance-and-Prestige-D": "TMLR Relevance and Prestige [D]",
  "Auto-简报-Stop-Just-Stop": "Stop, Just Stop",
  "Auto-简报-Stop-Making-TUIs": "Stop Making TUIs",
  "Auto-简报-Stagflation-Explained": "Stagflation Explained",
  "Auto-简报-Software-Engineering-in-the-Agentic-Era": "Software Engineering in the Agentic Era",
  "Auto-简报-Slapping-Windows-11-PCs-with-a-Copilot-key": "Slapping Windows 11 PCs with a Copilot k...",
  "Auto-简报-Simulation-the-new-Scaling-Law-—-Joon-Sung": "Simulation the new Scaling Law — Joon Su...",
  "Auto-简报-Show-HN-Make-your-logo-extra-bright-on-HDR": "Show HN Make your logo extra bright on H...",
  "Auto-简报-Show-HN-AgentSight-–-eBPF-observability-fo": "Show HN AgentSight – eBPF observability ...",
  "Auto-简报-Should-you-borrow-to-invest": "Should you borrow to invest",
  "Auto-简报-Scientists-release-biggest-2D-map-of-the-u": "Scientists release biggest 2D map of the...",
  "Auto-简报-Saplings-Unstable-Ground": "Saplings Unstable Ground",
  "Auto-简报-Samsung-Foundry-updates-process-roadmap-to": "Samsung Foundry updates process roadmap ...",
  "Auto-简报-SalesPatriot-YC-W25-Is-Hiring-Forward-Depl": "SalesPatriot YC W25 Is Hiring Forward De...",
  "Auto-简报-Rust-on-the-JVM-now-passes-99-of-official": "Rust on the JVM now passes 99 of officia...",
  "Auto-简报-Run-It-Hot-Yet-Again": "Run It Hot, Yet Again",
  "Auto-简报-Roblox-RBLX-Schlep-and-the-Streisand-Effec": "Roblox RBLX Schlep and the Streisand Eff...",
  "Auto-简报-Rebuilding-our-Electron-meeting-recording": "Rebuilding our Electron meeting-recordin...",
  "Auto-简报-Ranked-The-Worlds-Largest-Gold-Producers-2": "Ranked The Worlds Largest Gold Producers...",
  "Auto-简报-Ranked-The-Worlds-Largest-Cities-1950-2100": "Ranked The Worlds Largest Cities 1950-21...",
  "Auto-简报-Ranked-The-Worlds-Busiest-Airlines-by-Flig": "Ranked The Worlds Busiest Airlines by Fl...",
  "Auto-简报-Ranked-The-Most-Popular-AI-Tools-in-2026": "Ranked The Most Popular AI Tools in 2026",
  "Auto-简报-Ranked-The-Highest-Mountain-on-Every-Conti": "Ranked The Highest Mountain on Every Con...",
  "Auto-简报-Ranked-The-Biggest-Risks-to-the-US-Economy": "Ranked The Biggest Risks to the U.S. Eco...",
  "Auto-简报-Ranked-The-20-Highest-Grossing-Concert-Tou": "Ranked The 20 Highest-Grossing Concert T...",
  "Auto-简报-Ranked-Military-Spending-in-OECD-Countries": "Ranked Military Spending in OECD Countri...",
  "Auto-简报-Ranked-Countries-With-the-Highest-Senior-P": "Ranked Countries With the Highest Senior...",
  "Auto-简报-Ranked-Car-Brands-With-the-Most-Loyal-Cust": "Ranked Car Brands With the Most Loyal Cu...",
  "Auto-简报-QwenQwen38-27B-·-released": "QwenQwen3.8-27B · released",
  "Auto-简报-Qwen38-27B-is-identical-to-Qwen36-27B": "Qwen3.8-27B is identical to Qwen3.6-27B",
  "Auto-简报-Qwen38-27B-Q6-is-a-beast-at-agentic-coding": "Qwen3.8-27B Q6 is a beast at agentic cod...",
  "Auto-简报-Qwen-38-27B-scores-52-on-the-Artificial-An": "Qwen 3.8 27B scores 52 on the Artificial...",
  "Auto-简报-Qwen-38-27B-Released-Please-Share-Your-Exp": "Qwen 3.8 27B Released Please Share Your ...",
  "Auto-简报-Quoting-Matt-Webb": "Quoting Matt Webb",
  "Auto-简报-Quoting-Linus-Torvalds": "Quoting Linus Torvalds",
  "Auto-简报-PayPal-Declined": "PayPal, Declined",
  "Auto-简报-Past-the-Point-of-No-Return": "Past the Point of No Return",
  "Auto-简报-Overcaffeinated-in-Indonesia": "Overcaffeinated in Indonesia",
  "Auto-简报-Over-Target": "Over Target",
  "Auto-简报-Other-Python-forums-Stack-Overflow": "Other Python forums - Stack Overflow",
  "Auto-简报-OpenAIs-AI-Agents-Just-Crossed-A-Line": "OpenAIs AI Agents Just Crossed A Line",
  "Auto-简报-North-Korean-Messiah": "North Korean Messiah",
  "Auto-简报-NetBSD-and-My-Life-2005": "NetBSD and My Life 2005",
  "Auto-简报-NanoGPT-Speedrun-Frontier": "NanoGPT Speedrun Frontier",
  "Auto-简报-More-than-just-code-review": "More than just code review",
  "Auto-简报-MiniMax-Music3-released": "MiniMax-Music3 released!",
  "Auto-简报-Markdown-SVG-upgrades": "Markdown SVG upgrades",
  "Auto-简报-Mapped-Where-Young-Americans-Are-Buying-Ho": "Mapped Where Young Americans Are Buying ...",
  "Auto-简报-Mapped-Where-Homelessness-Rates-Are-Highes": "Mapped Where Homelessness Rates Are High...",
  "Auto-简报-Made-a-cake-for-my-boyfriends-birthday": "Made a cake for my boyfriends birthday",
  "Auto-简报-LiteLLM-YC-W23-Is-Hiring-–-Rust-Performanc": "LiteLLM YC W23 Is Hiring – Rust  Perform...",
  "Auto-简报-Leopolds-Fall": "Leopolds Fall",
  "Auto-简报-Learning-about-The-Unix-Time-Sharing-Syste": "Learning about The Unix Time-Sharing Sys...",
  "Auto-简报-Knowing-When-to-Stop-The-Art-of-Making-a-L": "Knowing When to Stop The Art of Making a...",
  "Auto-简报-Japan-tried-to-build-an-operating-system-f": "Japan tried to build an operating system...",
  "Auto-简报-JIT-Compiling-Code-in-5μs": "JIT Compiling Code in 5μs",
  "Auto-简报-Initial-focus-for-our-partnership-with-Mot": "Initial focus for our partnership with M...",
  "Auto-简报-Import-AI-469-Science-AI;-RSI-simulator;-a": "Import AI 469 Science AI; RSI simulator;...",
  "Auto-简报-Import-AI-468-23-RSI-ideas;-PostTrainBench": "Import AI 468 23 RSI ideas; PostTrainBen...",
  "Auto-简报-Import-AI-467-Self-sustaining-AI-viruses;": "Import AI 467 Self-sustaining AI viruses...",
  "Auto-简报-ITS-OUT": "ITS OUT",
  "Auto-简报-I-wrote-an-AI-textbook-—-how-long-until-AI": "I wrote an AI textbook — how long until ...",
  "Auto-简报-I-tested-Grok-Bot-Grok-46-and-Cursor-Origi": "I tested Grok Bot, Grok 4.6, and Cursor ...",
  "Auto-简报-I-gave-Qwen-38-27B-a-reverse-engineering-j": "I gave Qwen 3.8 27B a reverse-engineerin...",
  "Auto-简报-I-compiled-Dooms-renderer-into-a-21B-param": "I compiled Dooms renderer into a 21B-par...",
  "Auto-简报-How-is-the-qmusage-quota-for-Grok-46-in-cu": "How is the qmusage quota for Grok 4.6 in...",
  "Auto-简报-How-Much-Would-an-AI-Crash-Destroy": "How Much Would an AI Crash Destroy",
  "Auto-简报-How-Claude-Watermarks-AI-Generated-Text": "How Claude Watermarks AI-Generated Text",
  "Auto-简报-Hook-hold-harvest-and-hide-Metas-alleged-s": "Hook, hold, harvest and hide Metas alleg...",
  "Auto-简报-Hey-Rustaceans-Got-a-question-Ask-here-332": "Hey Rustaceans Got a question Ask here 3...",
  "Auto-简报-Here-We-Go-Again": "Here We Go Again",
  "Auto-简报-Here-Comes-the-Repo-Man": "Here Comes the Repo Man",
  "Auto-简报-Great-Scott": "Great Scott",
  "Auto-简报-Github-unslothai-unsloth": "Github__unslothai_unsloth",
  "Auto-简报-Github-smicallef-spiderfoot": "Github__smicallef_spiderfoot",
  "Auto-简报-Github-openai-codex": "Github__openai_codex",
  "Auto-简报-Github-obra-superpowers": "Github__obra_superpowers",
  "Auto-简报-Github-modular-modular": "Github__modular_modular",
  "Auto-简报-Github-megadose-holehe": "Github__megadose_holehe",
  "Auto-简报-Github-mattpocock-skills": "Github__mattpocock_skills",
  "Auto-简报-Github-cursor-plugins": "Github__cursor_plugins",
  "Auto-简报-Github-cordiverse-cordis": "Github__cordiverse_cordis",
  "Auto-简报-Github-affaan-m-ECC": "Github__affaan-m_ECC",
  "Auto-简报-Github-Wei-Shaw-sub2api": "Github__Wei-Shaw_sub2api",
  "Auto-简报-GLM-53-How-Chinese-labs-keep-stride-with-t": "GLM-5.3 How Chinese labs keep stride wit...",
  "Auto-简报-GLM-53-Released": "GLM 5.3 Released",
  "Auto-简报-Friday-Daily-Thread-rPython-Meta-and-Free": "Friday Daily Thread rPython Meta and Fre...",
  "Auto-简报-For-the-people-who-got-reviews-back-from-n": "For the people who got reviews back from...",
  "Auto-简报-Fixed-Jinja-chat-template-for-Qwen-35-36-a": "Fixed Jinja chat template for Qwen 3.5, ...",
  "Auto-简报-Finfluencer-Promotions-Are-Getting-Worse": "Finfluencer Promotions Are Getting Worse",
  "Auto-简报-Financing-the-AI-Boom-3": "Financing the AI Boom 3",
  "Auto-简报-Fast-and-Hard-Code": "Fast and Hard Code",
  "Auto-简报-Endangered-Specious": "Endangered Specious",
  "Auto-简报-Economists-should-be-worried-about-birth-r": "Economists should be worried about birth...",
  "Auto-简报-Early-Humans-Likely-Ate-Carbs-and-Sugary-F": "Early Humans Likely Ate Carbs and Sugary...",
  "Auto-简报-EU-GPU-prices-are-up-19-in-one-month-track": "EU GPU prices are up ~19 in one month, t...",
  "Auto-简报-Dirty-Secrets-Eight-SMIDs": "Dirty Secrets Eight SMIDs",
  "Auto-简报-Digging-the-grave-of-my-skills-Hollywood-c": "Digging the grave of my skills Hollywood...",
  "Auto-简报-Different-Strengths-Different-Weaknesses": "Different Strengths  Different Weaknesse...",
  "Auto-简报-DeepSeek-周末用量统一低价收费；特斯拉-9-月-3-日首秀-Cybercab": "DeepSeek 周末用量统一低价收费；特斯拉 9 月 3 日首秀 Cyberc...",
  "Auto-简报-DeepSeek-is-back-and-Silicon-Valley-is-ter": "DeepSeek is back... and Silicon Valley i...",
  "Auto-简报-DeepSeek-Just-Made-Closed-AI-Look-Ridiculo": "DeepSeek Just Made Closed AI Look Ridicu...",
  "Auto-简报-Controlling-Reasoning-Effort-in-LLMs": "Controlling Reasoning Effort in LLMs",
  "Auto-简报-Collaborative-Fund-Conversations-Jacob-Hod": "Collaborative Fund Conversations Jacob H...",
  "Auto-简报-Claudette-Make-Claude-Stop-Talking-Like-a": "Claudette Make Claude Stop Talking Like ...",
  "Auto-简报-Claude-AI-Failed-650-Times…Then-Beat-The-H": "Claude AI Failed 650 Times…Then Beat The...",
  "Auto-简报-City2Graph-A-Python-library-for-Heterogene": "City2Graph A Python library for Heteroge...",
  "Auto-简报-ChatGPT-search-now-uses-the-siteoperator-a": "ChatGPT search now uses the siteoperator...",
  "Auto-简报-Cerebrass-Next-Generation-CS-4-Fast-Just-G": "Cerebrass Next Generation CS-4 Fast Just...",
  "Auto-简报-Cancer-Related-Mortality-Among-US-Pilots-a": "Cancer-Related Mortality Among US Pilots...",
  "Auto-简报-Canadas-Condo-Conundrum": "Canadas Condo Conundrum",
  "Auto-简报-Canada-suspends-trade-negotiations-with-US": "Canada suspends trade negotiations with ...",
  "Auto-简报-Building-an-AI-Text-Detector-From-Scratch": "Building an AI Text Detector From Scratc...",
  "Auto-简报-Bringing-the-cybersecurity-capabilities-of": "Bringing the cybersecurity capabilities ...",
  "Auto-简报-Bill-Bernstein-The-Money-Decisions-That-Ac": "Bill Bernstein The Money Decisions That ...",
  "Auto-简报-Belgian-car-salesman-becomes-prince-after": "Belgian car salesman becomes prince afte...",
  "Auto-简报-Base-Power-Company-Chapter-3": "Base Power Company Chapter 3",
  "Auto-简报-Are-we-watching-the-US-go-bankrupt": "Are we watching the U.S. go bankrupt",
  "Auto-简报-Are-Open-Models-Catching-Up": "Are Open Models Catching Up",
  "Auto-简报-Anthropic-appears-to-be-AB-testing-reduced": "Anthropic appears to be AB testing reduc...",
  "Auto-简报-Another-Better-Lower-Bound-for-N17-Square": "Another Better Lower Bound for N17 Squar...",
  "Auto-简报-Announcing-Lennys-Jobs-The-best-place-in-t": "Announcing Lennys Jobs The best place in...",
  "Auto-简报-An-opinionated-guide-to-which-AI-to-use-to": "An opinionated guide to which AI to use ...",
  "Auto-简报-Americas-Electricity-Gap": "Americas Electricity Gap",
  "Auto-简报-All-You-Need-To-Know-About-Warsh": "All You Need To Know About Warsh",
  "Auto-简报-AMDs-FP64-Boost-with-MI430X-Is-Even-Bigger": "AMDs FP64 Boost with MI430X Is Even Bigg...",
  "Auto-简报-AI-时代的-Surface-Pro-7-改造指南：看板、轻量工作站与-Linux": "AI 时代的 Surface Pro 7 改造指南：看板、轻量工作站与 Linu...",
  "Auto-简报-AI-即将接管流量，而广告正在疯狂「末日反扑」": "AI 即将接管流量，而广告正在疯狂「末日反扑」",
  "Auto-简报-AI-Got-Good-at-Language-Now-Its-Learning-t": "AI Got Good at Language. Now Its Learnin...",
  "Auto-简报-A-shot-scraper-style-JSON-API-on-Bun-14s-n": "A shot-scraper-style JSON API on Bun 1.4...",
  "Auto-简报-A-preliminary-Qwen38-27B-model-card-is-liv": "A preliminary Qwen3.8-27B model card is ...",
  "Auto-简报-A-formal-degree-and-algorithmic-problem-so": "A formal degree and algorithmic problem-...",
  "Auto-简报-A-Minor-Detail": "A Minor Detail",
  "Auto-简报-A-Kantian-Critique-of-Sorry-by-Justin-Bieb": "A Kantian Critique of Sorry by Justin Bi...",
  "Auto-简报-A-Friendly-Introduction-to-Racket": "A Friendly Introduction to Racket",
  "Auto-简报-38x-in-Ten-Months-Inside-One-of-Fintechs-F": "38x in Ten Months Inside One of Fintechs...",
  "Auto-简报-29-Year-Olds-Can-Write-Memoirs-Too": "29-Year-Olds Can Write Memoirs Too",
  "Auto-简报-23-low-regret-recommendations-for-AI-polic": "23 low-regret recommendations for AI pol...",
  "Auto-简报-202634-App-Snore": "2026.34 App Snore",
  "Auto-简报-202633-The-CapEx-Train-Keeps-Rolling": "2026.33 The CapEx Train Keeps Rolling",
  "Auto-简报-12B-of-US-ratepayers-money-wasted-on-a-mod": "$12B of US ratepayers money wasted on a ..."
};
